In [1]:
from cayman_office_system import *

INFO:shining_pebbles:Shining Pebbles package initialized
INFO:numexpr.utils:Note: NumExpr detected 10 cores but "NUMEXPR_MAX_THREADS" not set, so enforcing safe limit of 8.
INFO:numexpr.utils:NumExpr defaulting to 8 threads.
/Users/juneyoungpark/anaconda3/lib/python3.11/site-packages/pandas/core/arrays/masked.py:60: UserWarning: Pandas requires version '1.3.6' or newer of 'bottleneck' (version '1.3.5' currently installed).
  from pandas.core import (

In [2]:
trades = Trades()

| import trade of (date, index) = (2024-09-02, None)
|- cash flow of trade: -614581438.0
| import trade of (date, index) = (2024-09-05, None)
|- cash flow of trade: -529470241.0
| import trade of (date, index) = (2024-09-06, None)
|- cash flow of trade: -91060069.0
| import trade of (date, index) = (2024-09-09, None)
|- cash flow of trade: -384482599.0
| import trade of (date, index) = (2024-09-10, None)
|- cash flow of trade: -625076151.0
| import trade of (date, index) = (2024-09-12, None)
|- cash flow of trade: -528686258.0
| import trade of (date, index) = (2024-09-13, None)
|- cash flow of trade: -519691172.0
| import trade of (date, index) = (2024-09-19, None)
|- cash flow of trade: -727234488.0
| import trade of (date, index) = (2024-09-20, None)
|- cash flow of trade: -1931465216.0
| import trade of (date, index) = (2024-09-23, None)
|- cash flow of trade: -726876600.0
| import trade of (date, index) = (2024-09-24, None)
|- cash flow of trade: -1282227226.0
| import trade of (date, index) = (2024-09-26, None)
|- cash flow of trade: -405884829.0
| import trade of (date, index) = (2024-10-08, None)
|- cash flow of trade: -670806496.0
| import trade of (date, index) = (2024-10-10, None)
|- cash flow of trade: -1479583697.0
| import trade of (date, index) = (2024-10-11, None)
|- cash flow of trade: -341436216.0
| append synthetic trade of Sell (date) = (2024-10-07)
|- cash flow of synthetic trade: 2984485100.0
| append synthetic trade of Sell (date) = (2024-10-07)
|- cash flow of synthetic trade: 33750000.0
| append synthetic trade of Buy (date) = (2024-10-08)
|- cash flow of synthetic trade: -2843520000.0

In [3]:
trades.history

,date,ticker,name,type,num_shares,price_average,net_amount,cash_flow
0,2024-09-02,003030 KS,SEAH STEEL HOLDINGS CORP,Buy,900,177645.666667,160040981.0,-160040981.0
1,2024-09-02,007340 KS,DN AUTOMOTIVE CORP,Buy,2500,88110.280000,220495976.0,-220495976.0
2,2024-09-02,271560 KS,ORION CORP/REPUBLIC OF KOREA,Buy,2200,91495.772727,201491991.0,-201491991.0
3,2024-09-02,282690 KS,DONG AH TIRE & RUBBER CO LTD,Buy,2500,13007.988000,32552490.0,-32552490.0
4,2024-09-05,003030 KS,SEAH STEEL HOLDINGS CORP,Buy,800,175209.750000,140307968.0,-140307968.0
...,...,...,...,...,...,...,...,...
64,2024-10-10,271560 KS,ORION CORP/REPUBLIC OF KOREA,Buy,3200,100062.375000,320519800.0,-320519800.0
65,2024-10-10,316140 KS,WOORI FINANCIAL GROUP INC,Buy,50000,16095.446200,805577082.0,-805577082.0
66,2024-10-10,007340 KS,DN AUTOMOTIVE CORP,Buy,8145,18878.147330,153916273.0,-153916273.0
67,2024-10-11,007340 KS,DN AUTOMOTIVE CORP,Buy,5000,18529.124000,92738266.0,-92738266.0
68,2024-10-11,271560 KS,ORION CORP/REPUBLIC OF KOREA,Buy,2500,99379.800000,248697950.0,-248697950.0

In [4]:
trades.get_pl_evaluated_of_buys()

,date,ticker,name,delta_shares,price_average,price_last,net_amount,evaluation,return
0,2024-09-02,003030 KS,SEAH STEEL HOLDINGS CORP,900,177645.666667,168100.0,160040981.0,151290000.0,-5.373431
1,2024-09-02,007340 KS,DN AUTOMOTIVE CORP,2500,88110.280000,93950.0,220495976.0,234875000.0,6.627740
2,2024-09-02,271560 KS,ORION CORP/REPUBLIC OF KOREA,2200,91495.772727,99800.0,201491991.0,219560000.0,9.076078
3,2024-09-02,282690 KS,DONG AH TIRE & RUBBER CO LTD,2500,13007.988000,13500.0,32552490.0,33750000.0,3.782384
4,2024-09-05,003030 KS,SEAH STEEL HOLDINGS CORP,800,175209.750000,168100.0,140307968.0,134480000.0,-4.057851
...,...,...,...,...,...,...,...,...,...
64,2024-10-10,271560 KS,ORION CORP/REPUBLIC OF KOREA,3200,100062.375000,99800.0,320519800.0,319360000.0,-0.262211
65,2024-10-10,316140 KS,WOORI FINANCIAL GROUP INC,50000,16095.446200,16540.0,805577082.0,827000000.0,2.761985
66,2024-10-10,007340 KS,DN AUTOMOTIVE CORP,8145,18878.147330,18790.0,153916273.0,153044550.0,-0.466928
67,2024-10-11,007340 KS,DN AUTOMOTIVE CORP,5000,18529.124000,18790.0,92738266.0,93950000.0,1.407924
68,2024-10-11,271560 KS,ORION CORP/REPUBLIC OF KOREA,2500,99379.800000,99800.0,248697950.0,249500000.0,0.422822

In [5]:
trades.get_pl_realized_of_sells()

KeyError: 'evaluation'

In [11]:
df = trades.merged_info.copy()
df = df[df['type'].isin(['Sell', 'Sell_synthetic'])]
df['realization'] = df['num_shares'] * df['price_last']
# def adjust_price(row):
#     if row['ticker'] == '007340 KS' and row['date'] <= '2024-10-07':
#         return row['price_last'] * 5
#     return row['price_last']
# # DN exceptions before '2024-10-07'
# df['price_last'] = df.apply(adjust_price, axis=1)
cols_to_keep = ['date', 'ticker', 'name', 'delta_shares', 'price_average', 'net_amount', 'realization']
df = df[cols_to_keep]
df

,date,ticker,name,delta_shares,price_average,price_last,net_amount,return
54,2024-10-07,282690 KS,DONG AH TIRE & RUBBER CO LTD,-2500,13500.0,13500.0,3.375000e+07,0.00000
55,2024-10-07,007340 KS,DN AUTOMOTIVE CORP,-29231,102100.0,93950.0,2.984485e+09,-7.98237

In [4]:
merged_info = trades.merged_info
merged_info_sell = merged_info[merged_info['type'].isin(['Sell', 'Sell_synthetic'])]
merged_info_sell

,date,name_x,ticker,type,num_shares,price_average,consideration,commission,net_amount,delta_shares,cash_flow,ticker_bbg,name_kr,name,market_index,sector,cap(/1e8),price_last
54,2024-10-07,DONG AH TIRE & RUBBER CO LTD,282690 KS,Sell_synthetic,2500,13500.0,3.375000e+07,0.0,3.375000e+07,-2500,3.375000e+07,282690 KS Equity,동아타이어,DONG AH TIRE & RUBBER CO LTD,KOSPI Index,Consumer Discretionary,1853.0,13500.0
55,2024-10-07,DN AUTOMOTIVE CORP,007340 KS,Sell_synthetic,29231,102100.0,2.984485e+09,0.0,2.984485e+09,-29231,2.984485e+09,007340 KS Equity,DN오토모티브,DN AUTOMOTIVE CORP,KOSPI Index,Consumer Discretionary,11380.0,18790.0

In [7]:
list(trades.history['date'])

['2024-09-02',
 '2024-09-02',
 '2024-09-02',
 '2024-09-02',
 '2024-09-05',
 '2024-09-05',
 '2024-09-05',
 '2024-09-06',
 '2024-09-09',
 '2024-09-09',
 '2024-09-09',
 '2024-09-10',
 '2024-09-10',
 '2024-09-10',
 '2024-09-10',
 '2024-09-12',
 '2024-09-12',
 '2024-09-12',
 '2024-09-12',
 '2024-09-13',
 '2024-09-13',
 '2024-09-13',
 '2024-09-13',
 '2024-09-19',
 '2024-09-19',
 '2024-09-19',
 '2024-09-19',
 '2024-09-19',
 '2024-09-20',
 '2024-09-20',
 '2024-09-20',
 '2024-09-20',
 '2024-09-20',
 '2024-09-20',
 '2024-09-20',
 '2024-09-23',
 '2024-09-23',
 '2024-09-23',
 '2024-09-23',
 '2024-09-23',
 '2024-09-23',
 '2024-09-23',
 '2024-09-24',
 '2024-09-24',
 '2024-09-24',
 '2024-09-24',
 '2024-09-24',
 '2024-09-24',
 '2024-09-26',
 '2024-09-26',
 '2024-09-26',
 '2024-09-26',
 '2024-09-26',
 '2024-09-26',
 '2024-10-07',
 '2024-10-07',
 '2024-10-08',
 '2024-10-08',
 '2024-10-08',
 '2024-10-08',
 '2024-10-08',
 '2024-10-10',
 '2024-10-10',
 '2024-10-10',
 '2024-10-10',
 '2024-10-10',
 '2024-10-10',
 '2024-10-11',
 '2024-10-11']

In [5]:
trades.get_merged_info(synthetic_trades=True)

| append synthetic trade of Sell (date) = (2024-10-07)
consideration: 2984485100
|- cash flow of synthetic trade: -2984485100.0
| append synthetic trade of Sell (date) = (2024-10-07)
consideration: 33750000
|- cash flow of synthetic trade: -33750000.0
| append synthetic trade of Buy (date) = (2024-10-08)
|- cash flow of synthetic trade: 2843520000.0

,date,name_x,ticker,type,num_shares,price_average,consideration,commission,net_amount,delta_shares,cash_flow,ticker_bbg,name_kr,name,market_index,sector,cap(/1e8),price_last
0,2024-09-02,SeAH Steel Holdings,003030 KS,Buy,900,177645.666667,1.598811e+08,159881.0,1.600410e+08,900,-1.600410e+08,003030 KS Equity,세아제강지주,SEAH STEEL HOLDINGS CORP,KOSPI Index,Materials,6962.0,168100.0
1,2024-09-02,DN AUTOMOTIVE,007340 KS,Buy,2500,88110.280000,2.202757e+08,220276.0,2.204960e+08,2500,-2.204960e+08,007340 KS Equity,DN오토모티브,DN AUTOMOTIVE CORP,KOSPI Index,Consumer Discretionary,11380.0,18790.0
2,2024-09-02,ORION,271560 KS,Buy,2200,91495.772727,2.012907e+08,201291.0,2.014920e+08,2200,-2.014920e+08,271560 KS Equity,오리온,ORION CORP/REPUBLIC OF KOREA,KOSPI Index,Consumer Staples,39457.0,99800.0
3,2024-09-02,DONG AH TIRE,282690 KS,Buy,2500,13007.988000,3.251997e+07,32520.0,3.255249e+07,2500,-3.255249e+07,282690 KS Equity,동아타이어,DONG AH TIRE & RUBBER CO LTD,KOSPI Index,Consumer Discretionary,1853.0,13500.0
4,2024-09-05,SeAH Steel Holdings,003030 KS,Buy,800,175209.750000,1.401678e+08,140168.0,1.403080e+08,800,-1.403080e+08,003030 KS Equity,세아제강지주,SEAH STEEL HOLDINGS CORP,KOSPI Index,Materials,6962.0,168100.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
64,2024-10-11,DN AUTOMOTIVE,007340 KS,Buy,5000,18529.124000,9.264562e+07,92646.0,9.273827e+07,5000,-9.273827e+07,007340 KS Equity,DN오토모티브,DN AUTOMOTIVE CORP,KOSPI Index,Consumer Discretionary,11380.0,18790.0
65,2024-10-11,ORION,271560 KS,Buy,2500,99379.800000,2.484495e+08,248450.0,2.486980e+08,2500,-2.486980e+08,271560 KS Equity,오리온,ORION CORP/REPUBLIC OF KOREA,KOSPI Index,Consumer Staples,39457.0,99800.0
66,2024-10-07,DN AUTOMOTIVE CORP,007340 KS,Sell_synthetic,29231,102100.000000,2.984485e+09,0.0,2.984485e+09,-29231,-2.984485e+09,007340 KS Equity,DN오토모티브,DN AUTOMOTIVE CORP,KOSPI Index,Consumer Discretionary,11380.0,18790.0
67,2024-10-07,DONG AH TIRE & RUBBER CO LTD,282690 KS,Sell_synthetic,2500,13500.000000,3.375000e+07,0.0,3.375000e+07,-2500,-3.375000e+07,282690 KS Equity,동아타이어,DONG AH TIRE & RUBBER CO LTD,KOSPI Index,Consumer Discretionary,1853.0,13500.0
68,2024-10-08,DN AUTOMOTIVE CORP,007340 KS,Buy_synthetic,148100,19200.000000,2.843520e+09,0.0,2.843520e+09,148100,2.843520e+09,007340 KS Equity,DN오토모티브,DN AUTOMOTIVE CORP,KOSPI Index,Consumer Discretionary,11380.0,18790.0

In [4]:
trades.history.tail(30)

,date,ticker,name,type,num_shares,price_average,net_amount,cash_flow
36,2024-09-23,003030 KS,SEAH STEEL HOLDINGS CORP,Buy,250,184116.400000,46075129.0,-46075129.0
37,2024-09-23,006040 KS,DONGWON INDUSTRIES CO LTD,Buy,2500,31479.360000,78777098.0,-78777098.0
38,2024-09-23,007340 KS,DN AUTOMOTIVE CORP,Buy,2000,100705.900000,201613212.0,-201613212.0
39,2024-09-23,023160 KS,TK CORPORATION,Buy,4500,14670.400000,66082817.0,-66082817.0
40,2024-09-23,271560 KS,ORION CORP/REPUBLIC OF KOREA,Buy,2200,93522.636364,205955550.0,-205955550.0
41,2024-09-23,316140 KS,WOORI FINANCIAL GROUP INC,Buy,2000,15652.175000,31335654.0,-31335654.0
42,2024-09-24,003030 KS,SEAH STEEL HOLDINGS CORP,Buy,500,189070.400000,94629735.0,-94629735.0
43,2024-09-24,006040 KS,DONGWON INDUSTRIES CO LTD,Buy,2500,31417.300000,78621793.0,-78621793.0
44,2024-09-24,007340 KS,DN AUTOMOTIVE CORP,Buy,6500,102404.169231,666292727.0,-666292727.0
45,2024-09-24,023160 KS,TK CORPORATION,Buy,7000,14643.414286,102606404.0,-102606404.0
46,2024-09-24,271560 KS,ORION CORP/REPUBLIC OF KOREA,Buy,2000,91738.300000,183660077.0,-183660077.0
47,2024-09-24,316140 KS,WOORI FINANCIAL GROUP INC,Buy,10000,15626.023000,156416490.0,-156416490.0
48,2024-09-26,000660 KS,SK HYNIX INC,Buy,500,179272.600000,89725936.0,-89725936.0
49,2024-09-26,003030 KS,SEAH STEEL HOLDINGS CORP,Buy,250,190126.800000,47579232.0,-47579232.0
50,2024-09-26,006040 KS,DONGWON INDUSTRIES CO LTD,Buy,2500,31283.520000,78287009.0,-78287009.0
51,2024-09-26,023160 KS,TK CORPORATION,Buy,5000,14731.052000,73728915.0,-73728915.0
52,2024-09-26,271560 KS,ORION CORP/REPUBLIC OF KOREA,Buy,800,95434.125000,76423647.0,-76423647.0
53,2024-09-26,316140 KS,WOORI FINANCIAL GROUP INC,Buy,2500,16039.996000,40140090.0,-40140090.0
54,2024-10-08,006040 KS,DONGWON INDUSTRIES CO LTD,Buy,2000,32032.600000,64129265.0,-64129265.0
55,2024-10-08,007340 KS,DN AUTOMOTIVE CORP,Buy,8000,18989.843750,152070669.0,-152070669.0
56,2024-10-08,023160 KS,TK CORPORATION,Buy,8000,13642.888750,109252253.0,-109252253.0
57,2024-10-08,271560 KS,ORION CORP/REPUBLIC OF KOREA,Buy,3500,98574.085714,345354309.0,-345354309.0
58,2024-10-10,000660 KS,SK HYNIX INC,Buy,500,185651.400000,92918526.0,-92918526.0
59,2024-10-10,006040 KS,DONGWON INDUSTRIES CO LTD,Buy,1350,32522.666667,43949506.0,-43949506.0
60,2024-10-10,007340 KS,DN AUTOMOTIVE CORP,Buy,8145,18878.147330,153916273.0,-153916273.0
61,2024-10-10,023160 KS,TK CORPORATION,Buy,4500,13919.971111,62702510.0,-62702510.0
62,2024-10-10,271560 KS,ORION CORP/REPUBLIC OF KOREA,Buy,3200,100062.375000,320519800.0,-320519800.0
63,2024-10-10,316140 KS,WOORI FINANCIAL GROUP INC,Buy,50000,16095.446200,805577082.0,-805577082.0
64,2024-10-11,007340 KS,DN AUTOMOTIVE CORP,Buy,5000,18529.124000,92738266.0,-92738266.0
65,2024-10-11,271560 KS,ORION CORP/REPUBLIC OF KOREA,Buy,2500,99379.800000,248697950.0,-248697950.0

In [3]:
trades.history

AttributeError: 'Trades' object has no attribute 'history'

In [2]:
DNDONGA_MERGER

[{'date': '2024-10-07',
  'ticker': '007340 KS',
  'type': 'Sell',
  'num_share': 29231},
 {'date': '2024-10-07',
  'ticker': '282690 KS',
  'type': 'Sell',
  'num_share': 2500,
  'trades_history': None},
 {'date': '2024-10-08',
  'ticker': '007340 KS',
  'type': 'Buy',
  'num_share': 148100,
  'trades_history': None}]

In [3]:
SyntheticTrades(DNDONGA_MERGER).df

| append synthetic trade of Sell (date) = (2024-10-07)
consideration: 2984485100
|- cash flow of synthetic trade: -2984485100.0
| append synthetic trade of Sell (date) = (2024-10-07)
consideration: 33750000
|- cash flow of synthetic trade: -33750000.0
| append synthetic trade of Buy (date) = (2024-10-08)
|- cash flow of synthetic trade: 2843520000.0

,date,name,ticker,type,num_shares,average_price,consideration,commission,net_amount,delta_shares,cash_flow
0,2024-10-07,DN AUTOMOTIVE CORP,007340 KS,Sell_synthetic,29231,102100,2984485100,0.0,2.984485e+09,-29231,-2.984485e+09
1,2024-10-07,DONG AH TIRE & RUBBER CO LTD,282690 KS,Sell_synthetic,2500,13500,33750000,0.0,3.375000e+07,-2500,-3.375000e+07
2,2024-10-08,DN AUTOMOTIVE CORP,007340 KS,Buy_synthetic,148100,19200,2843520000,0.0,2.843520e+09,148100,2.843520e+09

In [2]:
df_synthetic_dndong

NameError: name 'df_synthetic_dndong' is not defined

In [6]:
sell_dn = {
    'date': '2024-10-07',
    'ticker': '007340 KS',
    'type': 'Sell',
    'num_share': 29231,
}

sell_donga = {
    'date': '2024-10-07',
    'ticker': '282690 KS',
    'type': 'Sell',
    'num_share': 2500,
    'trades_history': None
}

buy_dn = {
    'date': '2024-10-08',
    'ticker': '007340 KS',
    'type': 'Buy',
    'num_share': 148100,
    'trades_history': None
}

In [7]:
trade_obj = SyntheticTrade(trade_data=buy_dn)
trade_obj.df

,date,name,ticker,type,num_shares,average_price,consideration,commission,net_amount,delta_shares,cash_flow
0,2024-10-08,DN AUTOMOTIVE CORP,007340 KS,Buy_synthetic,148100,19200,2843520000,0.0,2.843520e+09,148100,2.843520e+09

In [9]:
SyntheticTrade(trade_data=sell_dn).df
SyntheticTrade(trade_data=sell_donga).df

consideration: 2984485100
consideration: 33750000

,date,name,ticker,type,num_shares,average_price,consideration,commission,net_amount,delta_shares,cash_flow
0,2024-10-07,DONG AH TIRE & RUBBER CO LTD,282690 KS,Sell_synthetic,2500,13500,33750000,0.0,33750000.0,-2500,-33750000.0

In [5]:
trades = Trades()

NameError: name 'Trades' is not defined

In [3]:
trade_synthetic_dn = SyntheticTrade(date='2024-10-07', ticker='007340 KS', type='Sell', num_share=29231)
trade_synthetic_dn.get_df_synthetic_trade()

consideration: 2984485100

,date,name,ticker,type,num_shares,average_price,consideration,commission,net_amount,delta_shares,cash_flow
0,2024-10-07,DN AUTOMOTIVE CORP,007340 KS,Sell_synthetic,29231,102100,2984485100,0.0,2.984485e+09,-29231,-2.984485e+09

In [5]:
trade = Trade()

| import trade of (date, index) = (2024-10-11, -1)
|- cash flow of trade: -341436216.0

In [7]:
trade.df

,date,name,ticker,type,num_shares,average_price,consideration,commission,net_amount,delta_shares,cash_flow
0,2024-10-11,DN AUTOMOTIVE,007340 KS,Buy,5000,18529.124,92645620.0,92646,92738266.0,5000,-92738266.0
1,2024-10-11,ORION,271560 KS,Buy,2500,99379.800,248449500.0,248450,248697950.0,2500,-248697950.0

In [8]:
trade.df.columns

Index(['date', 'name', 'ticker', 'type', 'num_shares', 'average_price',
       'consideration', 'commission', 'net_amount', 'delta_shares',
       'cash_flow'],
      dtype='object')

In [2]:
trades = Trades()

| import trade of (date, index) = (2024-09-02, None)
|- cash flow of trade: -614581438.0
| import trade of (date, index) = (2024-09-05, None)
|- cash flow of trade: -529470241.0
| import trade of (date, index) = (2024-09-06, None)
|- cash flow of trade: -91060069.0
| import trade of (date, index) = (2024-09-09, None)
|- cash flow of trade: -384482599.0
| import trade of (date, index) = (2024-09-10, None)
|- cash flow of trade: -625076151.0
| import trade of (date, index) = (2024-09-12, None)
|- cash flow of trade: -528686258.0
| import trade of (date, index) = (2024-09-13, None)
|- cash flow of trade: -519691172.0
| import trade of (date, index) = (2024-09-19, None)
|- cash flow of trade: -727234488.0
| import trade of (date, index) = (2024-09-20, None)
|- cash flow of trade: -1931465216.0
| import trade of (date, index) = (2024-09-23, None)
|- cash flow of trade: -726876600.0
| import trade of (date, index) = (2024-09-24, None)
|- cash flow of trade: -1282227226.0
| import trade of (date, index) = (2024-09-26, None)
|- cash flow of trade: -405884829.0
| import trade of (date, index) = (2024-10-08, None)
|- cash flow of trade: -670806496.0
| import trade of (date, index) = (2024-10-10, None)
|- cash flow of trade: -1479583697.0
| import trade of (date, index) = (2024-10-11, None)
|- cash flow of trade: -341436216.0

In [3]:
trades.get_merged_info()

,date,name_x,ticker,type,num_shares,price_average,consideration,commission,net_amount,delta_shares,cash_flow,ticker_bbg,name_kr,name,market_index,sector,cap(/1e8),price_last
0,2024-09-02,SeAH Steel Holdings,003030 KS,Buy,900,177645.666667,159881100.0,159881,160040981.0,900,-160040981.0,003030 KS Equity,세아제강지주,SEAH STEEL HOLDINGS CORP,KOSPI Index,Materials,6962.0,168100.0
1,2024-09-02,DN AUTOMOTIVE,007340 KS,Buy,2500,88110.280000,220275700.0,220276,220495976.0,2500,-220495976.0,007340 KS Equity,DN오토모티브,DN AUTOMOTIVE CORP,KOSPI Index,Consumer Discretionary,11380.0,18790.0
2,2024-09-02,ORION,271560 KS,Buy,2200,91495.772727,201290700.0,201291,201491991.0,2200,-201491991.0,271560 KS Equity,오리온,ORION CORP/REPUBLIC OF KOREA,KOSPI Index,Consumer Staples,39457.0,99800.0
3,2024-09-02,DONG AH TIRE,282690 KS,Buy,2500,13007.988000,32519970.0,32520,32552490.0,2500,-32552490.0,282690 KS Equity,동아타이어,DONG AH TIRE & RUBBER CO LTD,KOSPI Index,Consumer Discretionary,1853.0,13500.0
4,2024-09-05,SeAH Steel Holdings,003030 KS,Buy,800,175209.750000,140167800.0,140168,140307968.0,800,-140307968.0,003030 KS Equity,세아제강지주,SEAH STEEL HOLDINGS CORP,KOSPI Index,Materials,6962.0,168100.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
61,2024-10-10,TKCORP.,023160 KS,Buy,4500,13919.971111,62639870.0,62640,62702510.0,4500,-62702510.0,023160 KS Equity,태광,TK CORPORATION,KOSDAQ Index,Industrials,3704.0,13980.0
62,2024-10-10,ORION,271560 KS,Buy,3200,100062.375000,320199600.0,320200,320519800.0,3200,-320519800.0,271560 KS Equity,오리온,ORION CORP/REPUBLIC OF KOREA,KOSPI Index,Consumer Staples,39457.0,99800.0
63,2024-10-10,WooriFinancialGroup,316140 KS,Buy,50000,16095.446200,804772310.0,804772,805577082.0,50000,-805577082.0,316140 KS Equity,우리금융지주,WOORI FINANCIAL GROUP INC,KOSPI Index,Financials,122824.0,16540.0
64,2024-10-11,DN AUTOMOTIVE,007340 KS,Buy,5000,18529.124000,92645620.0,92646,92738266.0,5000,-92738266.0,007340 KS Equity,DN오토모티브,DN AUTOMOTIVE CORP,KOSPI Index,Consumer Discretionary,11380.0,18790.0
65,2024-10-11,ORION,271560 KS,Buy,2500,99379.800000,248449500.0,248450,248697950.0,2500,-248697950.0,271560 KS Equity,오리온,ORION CORP/REPUBLIC OF KOREA,KOSPI Index,Consumer Staples,39457.0,99800.0

In [4]:
trades.get_history()

,date,ticker,name,type,num_shares,price_average,net_amount,cash_flow
0,2024-09-02,003030 KS,SEAH STEEL HOLDINGS CORP,Buy,900,177645.666667,160040981.0,-160040981.0
1,2024-09-02,007340 KS,DN AUTOMOTIVE CORP,Buy,2500,88110.280000,220495976.0,-220495976.0
2,2024-09-02,271560 KS,ORION CORP/REPUBLIC OF KOREA,Buy,2200,91495.772727,201491991.0,-201491991.0
3,2024-09-02,282690 KS,DONG AH TIRE & RUBBER CO LTD,Buy,2500,13007.988000,32552490.0,-32552490.0
4,2024-09-05,003030 KS,SEAH STEEL HOLDINGS CORP,Buy,800,175209.750000,140307968.0,-140307968.0
...,...,...,...,...,...,...,...,...
61,2024-10-10,023160 KS,TK CORPORATION,Buy,4500,13919.971111,62702510.0,-62702510.0
62,2024-10-10,271560 KS,ORION CORP/REPUBLIC OF KOREA,Buy,3200,100062.375000,320519800.0,-320519800.0
63,2024-10-10,316140 KS,WOORI FINANCIAL GROUP INC,Buy,50000,16095.446200,805577082.0,-805577082.0
64,2024-10-11,007340 KS,DN AUTOMOTIVE CORP,Buy,5000,18529.124000,92738266.0,-92738266.0
65,2024-10-11,271560 KS,ORION CORP/REPUBLIC OF KOREA,Buy,2500,99379.800000,248697950.0,-248697950.0

In [5]:
trades.get_pl_of_buys()

KeyError: "['price_lastnet_amount'] not in index"

In [6]:
trades.get_merged_info().columns

Index(['date', 'name_x', 'ticker', 'type', 'num_shares', 'average_price',
       'consideration', 'commission', 'net_amount', 'delta_shares',
       'cash_flow', 'ticker_bbg', 'name_kr', 'name_y', 'market_index',
       'sector', 'cap(/1e8)', 'price_last'],
      dtype='object')

In [5]:
trades.get_merged_info()

,date,name_x,ticker,type,num_shares,average_price,consideration,commission,net_amount,delta_shares,cash_flow,ticker_bbg,name_kr,name_y,market_index,sector,cap(/1e8),price_last
0,2024-09-02,SeAH Steel Holdings,003030 KS,Buy,900,177645.666667,159881100.0,159881,160040981.0,900,-160040981.0,003030 KS Equity,세아제강지주,SEAH STEEL HOLDINGS CORP,KOSPI Index,Materials,6962.0,168100.0
1,2024-09-02,DN AUTOMOTIVE,007340 KS,Buy,2500,88110.280000,220275700.0,220276,220495976.0,2500,-220495976.0,007340 KS Equity,DN오토모티브,DN AUTOMOTIVE CORP,KOSPI Index,Consumer Discretionary,11380.0,18790.0
2,2024-09-02,ORION,271560 KS,Buy,2200,91495.772727,201290700.0,201291,201491991.0,2200,-201491991.0,271560 KS Equity,오리온,ORION CORP/REPUBLIC OF KOREA,KOSPI Index,Consumer Staples,39457.0,99800.0
3,2024-09-02,DONG AH TIRE,282690 KS,Buy,2500,13007.988000,32519970.0,32520,32552490.0,2500,-32552490.0,282690 KS Equity,동아타이어,DONG AH TIRE & RUBBER CO LTD,KOSPI Index,Consumer Discretionary,1853.0,13500.0
4,2024-09-05,SeAH Steel Holdings,003030 KS,Buy,800,175209.750000,140167800.0,140168,140307968.0,800,-140307968.0,003030 KS Equity,세아제강지주,SEAH STEEL HOLDINGS CORP,KOSPI Index,Materials,6962.0,168100.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
61,2024-10-10,TKCORP.,023160 KS,Buy,4500,13919.971111,62639870.0,62640,62702510.0,4500,-62702510.0,023160 KS Equity,태광,TK CORPORATION,KOSDAQ Index,Industrials,3704.0,13980.0
62,2024-10-10,ORION,271560 KS,Buy,3200,100062.375000,320199600.0,320200,320519800.0,3200,-320519800.0,271560 KS Equity,오리온,ORION CORP/REPUBLIC OF KOREA,KOSPI Index,Consumer Staples,39457.0,99800.0
63,2024-10-10,WooriFinancialGroup,316140 KS,Buy,50000,16095.446200,804772310.0,804772,805577082.0,50000,-805577082.0,316140 KS Equity,우리금융지주,WOORI FINANCIAL GROUP INC,KOSPI Index,Financials,122824.0,16540.0
64,2024-10-11,DN AUTOMOTIVE,007340 KS,Buy,5000,18529.124000,92645620.0,92646,92738266.0,5000,-92738266.0,007340 KS Equity,DN오토모티브,DN AUTOMOTIVE CORP,KOSPI Index,Consumer Discretionary,11380.0,18790.0
65,2024-10-11,ORION,271560 KS,Buy,2500,99379.800000,248449500.0,248450,248697950.0,2500,-248697950.0,271560 KS Equity,오리온,ORION CORP/REPUBLIC OF KOREA,KOSPI Index,Consumer Staples,39457.0,99800.0

AttributeError: 'Trades' object has no attribute 'history'

In [2]:
trade = Trade()

- import trade of (date, index) = (2024-10-11, -1)
- cash flow of trade: -341436216.0

In [3]:
trade.df

,date,name,ticker,type,num_shares,average_price,consideration,commission,net_amount,delta_shares,cash_flow
0,2024-10-11,DN AUTOMOTIVE,007340 KS,Buy,5000,18529.124,92645620.0,92646,92738266.0,5000,-92738266.0
1,2024-10-11,ORION,271560 KS,Buy,2500,99379.800,248449500.0,248450,248697950.0,2500,-248697950.0

In [4]:
trade.data

[{'date': '2024-10-11',
  'ticker': '007340 KS',
  'type': 'Buy',
  'num_shares': 5000,
  'delta_shares': 5000},
 {'date': '2024-10-11',
  'ticker': '271560 KS',
  'type': 'Buy',
  'num_shares': 2500,
  'delta_shares': 2500}]

In [5]:
trade.df

,date,name,ticker,type,num_shares,average_price,consideration,commission,net_amount,delta_shares,cash_flow
0,2024-10-11,DN AUTOMOTIVE,007340 KS,Buy,5000,18529.124,92645620.0,92646,92738266.0,5000,-92738266.0
1,2024-10-11,ORION,271560 KS,Buy,2500,99379.800,248449500.0,248450,248697950.0,2500,-248697950.0

In [6]:
trade.timeseries

,"007340 KS: (2024-10-11, 5000)","271560 KS: (2024-10-11, 2500)",evaluation: 2024-10-11,cumreturn: 2024-10-11
date,,,,
2024-10-11,93250000,247500000,340750000,0.00000
2024-10-14,93950000,249500000,343450000,0.79237

In [7]:
trades = Trades()

- import trade of (date, index) = (2024-09-02, None)
- cash flow of trade: -614581438.0
- import trade of (date, index) = (2024-09-05, None)
- cash flow of trade: -529470241.0
- import trade of (date, index) = (2024-09-06, None)
- cash flow of trade: -91060069.0
- import trade of (date, index) = (2024-09-09, None)
- cash flow of trade: -384482599.0
- import trade of (date, index) = (2024-09-10, None)
- cash flow of trade: -625076151.0
- import trade of (date, index) = (2024-09-12, None)
- cash flow of trade: -528686258.0
- import trade of (date, index) = (2024-09-13, None)
- cash flow of trade: -519691172.0
- import trade of (date, index) = (2024-09-19, None)
- cash flow of trade: -727234488.0
- import trade of (date, index) = (2024-09-20, None)
- cash flow of trade: -1931465216.0
- import trade of (date, index) = (2024-09-23, None)
- cash flow of trade: -726876600.0
- import trade of (date, index) = (2024-09-24, None)
- cash flow of trade: -1282227226.0
- import trade of (date, index) = (2024-09-26, None)
- cash flow of trade: -405884829.0
- import trade of (date, index) = (2024-10-08, None)
- cash flow of trade: -670806496.0
- import trade of (date, index) = (2024-10-10, None)
- cash flow of trade: -1479583697.0
- import trade of (date, index) = (2024-10-11, None)
- cash flow of trade: -341436216.0

KeyError: 'cash_flow'

In [7]:
trades.history

,date,name,ticker,type,num_shares,average_price,consideration,commission,net_amount
0,2024-09-02,SeAH Steel Holdings,003030 KS,Buy,900,177645.666667,159881100.0,159881.0,160040981.0
1,2024-09-02,DN AUTOMOTIVE,007340 KS,Buy,2500,88110.280000,220275700.0,220276.0,220495976.0
2,2024-09-02,ORION,271560 KS,Buy,2200,91495.772727,201290700.0,201291.0,201491991.0
3,2024-09-02,DONG AH TIRE,282690 KS,Buy,2500,13007.988000,32519970.0,32520.0,32552490.0
4,2024-09-05,SeAH Steel Holdings,003030 KS,Buy,800,175209.750000,140167800.0,140168.0,140307968.0
...,...,...,...,...,...,...,...,...,...
64,2024-10-10,ORION,271560 KS,Buy,3200,100062.375000,320199600.0,320200.0,320519800.0
65,2024-10-10,WooriFinancialGroup,316140 KS,Buy,50000,16095.446200,804772310.0,804772.0,805577082.0
66,2024-10-10,DN AUTOMOTIVE,007340 KS,Buy,8145,18878.147330,153762510.0,153763.0,153916273.0
67,2024-10-11,DN AUTOMOTIVE,007340 KS,Buy,5000,18529.124000,92645620.0,92646.0,92738266.0
68,2024-10-11,ORION,271560 KS,Buy,2500,99379.800000,248449500.0,248450.0,248697950.0