In [1]:
from cayman_office_system import *

INFO:shining_pebbles:Shining Pebbles package initialized
INFO:numexpr.utils:Note: NumExpr detected 10 cores but "NUMEXPR_MAX_THREADS" not set, so enforcing safe limit of 8.
INFO:numexpr.utils:NumExpr defaulting to 8 threads.
/Users/juneyoungpark/anaconda3/lib/python3.11/site-packages/pandas/core/arrays/masked.py:60: UserWarning: Pandas requires version '1.3.6' or newer of 'bottleneck' (version '1.3.5' currently installed).
  from pandas.core import (

In [2]:
trds = Trades()
trds

- import trade of (date, index) = (2024-09-02, None)
- net_amount: 614581438.0
- import trade of (date, index) = (2024-09-05, None)
- net_amount: 529470241.0
- import trade of (date, index) = (2024-09-06, None)
- net_amount: 91060069.0
- import trade of (date, index) = (2024-09-09, None)
- net_amount: 384482599.0
- import trade of (date, index) = (2024-09-10, None)
- net_amount: 625076151.0
- import trade of (date, index) = (2024-09-12, None)
- net_amount: 528686258.0
- import trade of (date, index) = (2024-09-13, None)
- net_amount: 519691172.0
- import trade of (date, index) = (2024-09-19, None)
- net_amount: 727234488.0
- import trade of (date, index) = (2024-09-20, None)
- net_amount: 1931465216.0
- import trade of (date, index) = (2024-09-23, None)
- net_amount: 726876600.0
- import trade of (date, index) = (2024-09-24, None)
- net_amount: 1282227226.0
- import trade of (date, index) = (2024-09-26, None)
- net_amount: 405884829.0

In [8]:
trds.timeseries_evaluation

,evaluation: 2024-09-02,evaluation: 2024-09-05,evaluation: 2024-09-06,evaluation: 2024-09-09,evaluation: 2024-09-10,evaluation: 2024-09-12,evaluation: 2024-09-13,evaluation: 2024-09-19,evaluation: 2024-09-20,evaluation: 2024-09-23,evaluation: 2024-09-24,evaluation: 2024-09-26,total_evaluation
date,,,,,,,,,,,,,
2024-09-02,612540000.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.000000e+00,0.0,0.000000e+00,0.0,6.125400e+08
2024-09-03,626465000.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.000000e+00,0.0,0.000000e+00,0.0,6.264650e+08
2024-09-04,612540000.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.000000e+00,0.0,0.000000e+00,0.0,6.125400e+08
2024-09-05,617490000.0,530610000.0,0.0,0.0,0.0,0.0,0.0,0.0,0.000000e+00,0.0,0.000000e+00,0.0,1.148100e+09
2024-09-06,613320000.0,526580000.0,90400000.0,0.0,0.0,0.0,0.0,0.0,0.000000e+00,0.0,0.000000e+00,0.0,1.230300e+09
2024-09-07,613320000.0,526580000.0,90400000.0,0.0,0.0,0.0,0.0,0.0,0.000000e+00,0.0,0.000000e+00,0.0,1.230300e+09
2024-09-08,613320000.0,526580000.0,90400000.0,0.0,0.0,0.0,0.0,0.0,0.000000e+00,0.0,0.000000e+00,0.0,1.230300e+09
2024-09-09,621840000.0,535100000.0,94200000.0,386310200.0,0.0,0.0,0.0,0.0,0.000000e+00,0.0,0.000000e+00,0.0,1.637450e+09
2024-09-10,601220000.0,515810000.0,89900000.0,371566900.0,622030000.0,0.0,0.0,0.0,0.000000e+00,0.0,0.000000e+00,0.0,2.200527e+09
2024-09-11,605520000.0,520160000.0,91800000.0,375555800.0,630620000.0,0.0,0.0,0.0,0.000000e+00,0.0,0.000000e+00,0.0,2.223656e+09
2024-09-12,621880000.0,534990000.0,93900000.0,385990900.0,655330000.0,529400000.0,0.0,0.0,0.000000e+00,0.0,0.000000e+00,0.0,2.821491e+09
2024-09-13,615260000.0,528720000.0,92400000.0,381094400.0,642140000.0,518725000.0,518725000.0,0.0,0.000000e+00,0.0,0.000000e+00,0.0,3.297064e+09
2024-09-14,615260000.0,528720000.0,92400000.0,381094400.0,642140000.0,518725000.0,518725000.0,0.0,0.000000e+00,0.0,0.000000e+00,0.0,3.297064e+09
2024-09-15,615260000.0,528720000.0,92400000.0,381094400.0,642140000.0,518725000.0,518725000.0,0.0,0.000000e+00,0.0,0.000000e+00,0.0,3.297064e+09
2024-09-16,615260000.0,528720000.0,92400000.0,381094400.0,642140000.0,518725000.0,518725000.0,0.0,0.000000e+00,0.0,0.000000e+00,0.0,3.297064e+09
2024-09-17,615260000.0,528720000.0,92400000.0,381094400.0,642140000.0,518725000.0,518725000.0,0.0,0.000000e+00,0.0,0.000000e+00,0.0,3.297064e+09
2024-09-18,615260000.0,528720000.0,92400000.0,381094400.0,642140000.0,518725000.0,518725000.0,0.0,0.000000e+00,0.0,0.000000e+00,0.0,3.297064e+09
2024-09-19,633940000.0,546110000.0,95900000.0,394152900.0,645210000.0,516490000.0,516490000.0,728005000.0,0.000000e+00,0.0,0.000000e+00,0.0,4.076298e+09
2024-09-20,657090000.0,568360000.0,102200000.0,412208200.0,674320000.0,534250000.0,534250000.0,745333000.0,1.930805e+09,0.0,0.000000e+00,0.0,6.158816e+09
2024-09-21,657090000.0,568360000.0,102200000.0,412208200.0,674320000.0,534250000.0,534250000.0,745333000.0,1.930805e+09,0.0,0.000000e+00,0.0,6.158816e+09
2024-09-22,657090000.0,568360000.0,102200000.0,412208200.0,674320000.0,534250000.0,534250000.0,745333000.0,1.930805e+09,0.0,0.000000e+00,0.0,6.158816e+09
2024-09-23,656650000.0,567240000.0,101200000.0,410477200.0,678640000.0,541010000.0,541010000.0,747642800.0,1.945920e+09,726985000.0,0.000000e+00,0.0,6.916775e+09
2024-09-24,663790000.0,574070000.0,102100000.0,415535100.0,683910000.0,545245000.0,545245000.0,754028700.0,1.956060e+09,729415000.0,1.283070e+09,0.0,8.252469e+09
2024-09-25,662080000.0,572270000.0,102100000.0,414185100.0,686610000.0,547720000.0,547720000.0,749255000.0,1.952660e+09,730470000.0,1.278880e+09,0.0,8.243950e+09
2024-09-26,669460000.0,578550000.0,102100000.0,417885100.0,707890000.0,570290000.0,570290000.0,762811200.0,1.994580e+09,747760000.0,1.292380e+09,406910000.0,8.820906e+09
2024-09-27,670570000.0,578930000.0,102100000.0,417635100.0,713610000.0,576325000.0,576325000.0,756799500.0,1.996495e+09,752930000.0,1.289385e+09,405880000.0,8.836985e+09
2024-09-28,670570000.0,578930000.0,102100000.0,417635100.0,713610000.0,576325000.0,576325000.0,756799500.0,1.996495e+09,752930000.0,1.289385e+09,405880000.0,8.836985e+09
2024-09-29,670570000.0,578930000.0,102100000.0,417635100.0,713610000.0,576325000.0,576325000.0,756799500.0,1.996495e+09,752930000.0,1.289385e+09,405880000.0,8.836985e+09
2024-09-30,660280000.0,570110000.0,102100000.0,412385100.0,699210000.0,560140000.0,560140000.0,741025800.0,1.954570e+09,736980000.0,1.273870e+09,393400000.0,8.664211e+09
2024-10-01,660280000.0,570110000.0,102100000.0,412385100.0,699210000.0,560140000.0,560140000.0,741025800.0,1.954570e+09,736980000.0,1.273870e+09,393400000.0,8.664211e+09

In [9]:
fund = CaymanFund(trades=trds)

In [13]:
fund.get_timeseries()

,cash_usd,cash_krw,stock_usd,stock_krw,nav_usd,nav_krw,weight_cash_usd,weight_stock_usd,weight_cash_krw,weight_stock_krw
date,,,,,,,,,,
2024-09-01,1.533081e+07,2.050955e+10,0.000000e+00,0.000000e+00,1.533081e+07,2.050955e+10,100.000000,0.000000,100.000000,0.000000
2024-09-02,1.487160e+07,1.990340e+10,4.576830e+05,6.125400e+08,1.532928e+07,2.051594e+10,97.014322,2.985678,97.014322,2.985678
2024-09-03,1.487160e+07,1.995620e+10,4.668492e+05,6.264650e+08,1.533845e+07,2.058266e+10,96.956346,3.043654,96.956346,3.043654
2024-09-04,1.487160e+07,1.995620e+10,4.564722e+05,6.125400e+08,1.532807e+07,2.056874e+10,97.021985,2.978015,97.021985,2.978015
2024-09-05,1.447486e+07,1.931742e+10,8.602900e+05,1.148100e+09,1.533515e+07,2.046552e+10,94.390077,5.609923,94.390077,5.609923
2024-09-06,1.440665e+07,1.923287e+10,9.215730e+05,1.230300e+09,1.532822e+07,2.046317e+10,93.987736,6.012264,93.987736,6.012264
2024-09-07,1.440665e+07,1.923287e+10,9.215730e+05,1.230300e+09,1.532822e+07,2.046317e+10,93.987736,6.012264,93.987736,6.012264
2024-09-08,1.440665e+07,1.923287e+10,9.215730e+05,1.230300e+09,1.532822e+07,2.046317e+10,93.987736,6.012264,93.987736,6.012264
2024-09-09,1.411865e+07,1.884839e+10,1.226554e+06,1.637450e+09,1.534520e+07,2.048584e+10,92.006918,7.993082,92.006918,7.993082
2024-09-10,1.365356e+07,1.835038e+10,1.637297e+06,2.200527e+09,1.529086e+07,2.055091e+10,89.292314,10.707686,89.292314,10.707686
2024-09-11,1.365356e+07,1.829987e+10,1.659073e+06,2.223656e+09,1.531263e+07,2.052352e+10,89.165330,10.834670,89.165330,10.834670
2024-09-12,1.325961e+07,1.779439e+10,2.102452e+06,2.821491e+09,1.536206e+07,2.061588e+10,86.313993,13.686007,86.313993,13.686007
2024-09-13,1.286990e+07,1.716266e+10,2.472397e+06,3.297064e+09,1.534230e+07,2.045972e+10,83.885095,16.114905,83.885095,16.114905
2024-09-14,1.286990e+07,1.716266e+10,2.472397e+06,3.297064e+09,1.534230e+07,2.045972e+10,83.885095,16.114905,83.885095,16.114905
2024-09-15,1.286990e+07,1.716266e+10,2.472397e+06,3.297064e+09,1.534230e+07,2.045972e+10,83.885095,16.114905,83.885095,16.114905
2024-09-16,1.286990e+07,1.716266e+10,2.472397e+06,3.297064e+09,1.534230e+07,2.045972e+10,83.885095,16.114905,83.885095,16.114905
2024-09-17,1.286990e+07,1.716266e+10,2.472397e+06,3.297064e+09,1.534230e+07,2.045972e+10,83.885095,16.114905,83.885095,16.114905
2024-09-18,1.286990e+07,1.716266e+10,2.472397e+06,3.297064e+09,1.534230e+07,2.045972e+10,83.885095,16.114905,83.885095,16.114905
2024-09-19,1.232272e+07,1.637751e+10,3.067076e+06,4.076298e+09,1.538979e+07,2.045380e+10,80.070711,19.929289,80.070711,19.929289
2024-09-20,1.087614e+07,1.452183e+10,4.612654e+06,6.158816e+09,1.548880e+07,2.068064e+10,70.219415,29.780585,70.219415,29.780585
2024-09-21,1.087614e+07,1.452183e+10,4.612654e+06,6.158816e+09,1.548880e+07,2.068064e+10,70.219415,29.780585,70.219415,29.780585
2024-09-22,1.087614e+07,1.452183e+10,4.612654e+06,6.158816e+09,1.548880e+07,2.068064e+10,70.219415,29.780585,70.219415,29.780585
2024-09-23,1.033177e+07,1.379549e+10,5.180135e+06,6.916775e+09,1.551190e+07,2.071227e+10,66.605420,33.394580,66.605420,33.394580
2024-09-24,9.368629e+06,1.247246e+10,6.198805e+06,8.252469e+09,1.556743e+07,2.072492e+10,60.180946,39.819054,60.180946,39.819054
2024-09-25,9.368629e+06,1.251180e+10,6.172932e+06,8.243950e+09,1.554156e+07,2.075575e+10,60.281134,39.718866,60.281134,39.718866
2024-09-26,9.059435e+06,1.189250e+10,6.719564e+06,8.820906e+09,1.577900e+07,2.071341e+10,57.414510,42.585490,57.414510,42.585490
2024-09-27,9.059435e+06,1.185246e+10,6.754555e+06,8.836985e+09,1.581399e+07,2.068944e+10,57.287471,42.712529,57.287471,42.712529
2024-09-28,9.059435e+06,1.185246e+10,6.754555e+06,8.836985e+09,1.581399e+07,2.068944e+10,57.287471,42.712529,57.287471,42.712529
2024-09-29,9.059435e+06,1.185246e+10,6.754555e+06,8.836985e+09,1.581399e+07,2.068944e+10,57.287471,42.712529,57.287471,42.712529
2024-09-30,9.059435e+06,1.192829e+10,6.580397e+06,8.664211e+09,1.563983e+07,2.059250e+10,57.925400,42.074600,57.925400,42.074600
2024-10-01,9.059435e+06,1.192829e+10,6.580397e+06,8.664211e+09,1.563983e+07,2.059250e+10,57.925400,42.074600,57.925400,42.074600

In [10]:
frame = fund.frame
frame

            initial_balance_usd
date
2024-09-01           15330806.5

In [11]:
amounts = trds.timeseries_amount
amounts

            amount_order  total_amount_order
date
2024-09-02  6.145814e+08        6.145814e+08
2024-09-05  5.294702e+08        1.144052e+09
2024-09-06  9.106007e+07        1.235112e+09
2024-09-09  3.844826e+08        1.619594e+09
2024-09-10  6.250762e+08        2.244670e+09
2024-09-12  5.286863e+08        2.773357e+09
2024-09-13  5.196912e+08        3.293048e+09
2024-09-19  7.272345e+08        4.020282e+09
2024-09-20  1.931465e+09        5.951748e+09
2024-09-23  7.268766e+08        6.678624e+09
2024-09-24  1.282227e+09        7.960851e+09
2024-09-26  4.058848e+08        8.366736e+09

In [12]:
df = frame.merge(amounts[['amount_order']], how='outer', left_index=True, right_index=True)
df

            initial_balance_usd  amount_order
date
2024-09-01           15330806.5           NaN
2024-09-02                  NaN  6.145814e+08
2024-09-05                  NaN  5.294702e+08
2024-09-06                  NaN  9.106007e+07
2024-09-09                  NaN  3.844826e+08
2024-09-10                  NaN  6.250762e+08
2024-09-12                  NaN  5.286863e+08
2024-09-13                  NaN  5.196912e+08
2024-09-19                  NaN  7.272345e+08
2024-09-20                  NaN  1.931465e+09
2024-09-23                  NaN  7.268766e+08
2024-09-24                  NaN  1.282227e+09
2024-09-26                  NaN  4.058848e+08

In [42]:
fund.initial_date

'2024-09-01'

In [43]:
all_dates = get_date_range(fund.initial_date, get_today())
all_dates

['2024-09-01',
 '2024-09-02',
 '2024-09-03',
 '2024-09-04',
 '2024-09-05',
 '2024-09-06',
 '2024-09-07',
 '2024-09-08',
 '2024-09-09',
 '2024-09-10',
 '2024-09-11',
 '2024-09-12',
 '2024-09-13',
 '2024-09-14',
 '2024-09-15',
 '2024-09-16',
 '2024-09-17',
 '2024-09-18',
 '2024-09-19',
 '2024-09-20',
 '2024-09-21',
 '2024-09-22',
 '2024-09-23',
 '2024-09-24',
 '2024-09-25',
 '2024-09-26',
 '2024-09-27',
 '2024-09-28',
 '2024-09-29',
 '2024-09-30',
 '2024-10-01']

In [44]:
all_dates = get_date_range(fund.initial_date, get_today())
df = df.reindex(all_dates)
df

            initial_balance_usd  amount_order
date
2024-09-01           15330806.5           NaN
2024-09-02                  NaN  6.145814e+08
2024-09-03                  NaN           NaN
2024-09-04                  NaN           NaN
2024-09-05                  NaN  5.294702e+08
2024-09-06                  NaN  9.106007e+07
2024-09-07                  NaN           NaN
2024-09-08                  NaN           NaN
2024-09-09                  NaN  3.844826e+08
2024-09-10                  NaN  6.250762e+08
2024-09-11                  NaN           NaN
2024-09-12                  NaN  5.286863e+08
2024-09-13                  NaN  5.196912e+08
2024-09-14                  NaN           NaN
2024-09-15                  NaN           NaN
2024-09-16                  NaN           NaN
2024-09-17                  NaN           NaN
2024-09-18                  NaN           NaN
2024-09-19                  NaN  7.272345e+08
2024-09-20                  NaN  1.931465e+09
2024-09-21                  NaN           NaN
2024-09-22                  NaN           NaN
2024-09-23                  NaN  7.268766e+08
2024-09-24                  NaN  1.282227e+09
2024-09-25                  NaN           NaN
2024-09-26                  NaN  4.058848e+08
2024-09-27                  NaN           NaN
2024-09-28                  NaN           NaN
2024-09-29                  NaN           NaN
2024-09-30                  NaN           NaN
2024-10-01                  NaN           NaN

In [45]:
df['initial_balance_usd'] = df['initial_balance_usd'].ffill()
df['amount_order'] = df['amount_order'].fillna(0)
df['usdkrw'] = df.index.map(get_usdkrw_of_date)
df

            initial_balance_usd  amount_order   usdkrw
date
2024-09-01           15330806.5  0.000000e+00  1337.80
2024-09-02           15330806.5  6.145814e+08  1338.35
2024-09-03           15330806.5  0.000000e+00  1341.90
2024-09-04           15330806.5  0.000000e+00  1341.90
2024-09-05           15330806.5  5.294702e+08  1334.55
2024-09-06           15330806.5  9.106007e+07  1335.00
2024-09-07           15330806.5  0.000000e+00  1335.00
2024-09-08           15330806.5  0.000000e+00  1335.00
2024-09-09           15330806.5  3.844826e+08  1335.00
2024-09-10           15330806.5  6.250762e+08  1344.00
2024-09-11           15330806.5  0.000000e+00  1340.30
2024-09-12           15330806.5  5.286863e+08  1342.00
2024-09-13           15330806.5  5.196912e+08  1333.55
2024-09-14           15330806.5  0.000000e+00  1333.55
2024-09-15           15330806.5  0.000000e+00  1333.55
2024-09-16           15330806.5  0.000000e+00  1333.55
2024-09-17           15330806.5  0.000000e+00  1333.55
2024-09-18           15330806.5  0.000000e+00  1333.55
2024-09-19           15330806.5  7.272345e+08  1329.05
2024-09-20           15330806.5  1.931465e+09  1335.20
2024-09-21           15330806.5  0.000000e+00  1335.20
2024-09-22           15330806.5  0.000000e+00  1335.20
2024-09-23           15330806.5  7.268766e+08  1335.25
2024-09-24           15330806.5  1.282227e+09  1331.30
2024-09-25           15330806.5  0.000000e+00  1335.50
2024-09-26           15330806.5  4.058848e+08  1312.72
2024-09-27           15330806.5  0.000000e+00  1308.30
2024-09-28           15330806.5  0.000000e+00  1308.30
2024-09-29           15330806.5  0.000000e+00  1308.30
2024-09-30           15330806.5  0.000000e+00  1316.67
2024-10-01           15330806.5  0.000000e+00  1316.67

In [46]:
df['amount_usd'] = df['amount_order'] / df['usdkrw']
df

            initial_balance_usd  amount_order   usdkrw    amount_usd
date
2024-09-01           15330806.5  0.000000e+00  1337.80  0.000000e+00
2024-09-02           15330806.5  6.145814e+08  1338.35  4.592083e+05
2024-09-03           15330806.5  0.000000e+00  1341.90  0.000000e+00
2024-09-04           15330806.5  0.000000e+00  1341.90  0.000000e+00
2024-09-05           15330806.5  5.294702e+08  1334.55  3.967407e+05
2024-09-06           15330806.5  9.106007e+07  1335.00  6.820979e+04
2024-09-07           15330806.5  0.000000e+00  1335.00  0.000000e+00
2024-09-08           15330806.5  0.000000e+00  1335.00  0.000000e+00
2024-09-09           15330806.5  3.844826e+08  1335.00  2.880019e+05
2024-09-10           15330806.5  6.250762e+08  1344.00  4.650864e+05
2024-09-11           15330806.5  0.000000e+00  1340.30  0.000000e+00
2024-09-12           15330806.5  5.286863e+08  1342.00  3.939540e+05
2024-09-13           15330806.5  5.196912e+08  1333.55  3.897051e+05
2024-09-14           15330806.5  0.000000e+00  1333.55  0.000000e+00
2024-09-15           15330806.5  0.000000e+00  1333.55  0.000000e+00
2024-09-16           15330806.5  0.000000e+00  1333.55  0.000000e+00
2024-09-17           15330806.5  0.000000e+00  1333.55  0.000000e+00
2024-09-18           15330806.5  0.000000e+00  1333.55  0.000000e+00
2024-09-19           15330806.5  7.272345e+08  1329.05  5.471837e+05
2024-09-20           15330806.5  1.931465e+09  1335.20  1.446574e+06
2024-09-21           15330806.5  0.000000e+00  1335.20  0.000000e+00
2024-09-22           15330806.5  0.000000e+00  1335.20  0.000000e+00
2024-09-23           15330806.5  7.268766e+08  1335.25  5.443749e+05
2024-09-24           15330806.5  1.282227e+09  1331.30  9.631392e+05
2024-09-25           15330806.5  0.000000e+00  1335.50  0.000000e+00
2024-09-26           15330806.5  4.058848e+08  1312.72  3.091938e+05
2024-09-27           15330806.5  0.000000e+00  1308.30  0.000000e+00
2024-09-28           15330806.5  0.000000e+00  1308.30  0.000000e+00
2024-09-29           15330806.5  0.000000e+00  1308.30  0.000000e+00
2024-09-30           15330806.5  0.000000e+00  1316.67  0.000000e+00
2024-10-01           15330806.5  0.000000e+00  1316.67  0.000000e+00

In [47]:
df['cash_usd'] = df['initial_balance_usd'] - df['amount_usd'].cumsum()
df

,initial_balance_usd,amount_order,usdkrw,amount_usd,cash_usd
date,,,,,
2024-09-01,15330806.5,0.000000e+00,1337.80,0.000000e+00,1.533081e+07
2024-09-02,15330806.5,6.145814e+08,1338.35,4.592083e+05,1.487160e+07
2024-09-03,15330806.5,0.000000e+00,1341.90,0.000000e+00,1.487160e+07
2024-09-04,15330806.5,0.000000e+00,1341.90,0.000000e+00,1.487160e+07
2024-09-05,15330806.5,5.294702e+08,1334.55,3.967407e+05,1.447486e+07
2024-09-06,15330806.5,9.106007e+07,1335.00,6.820979e+04,1.440665e+07
2024-09-07,15330806.5,0.000000e+00,1335.00,0.000000e+00,1.440665e+07
2024-09-08,15330806.5,0.000000e+00,1335.00,0.000000e+00,1.440665e+07
2024-09-09,15330806.5,3.844826e+08,1335.00,2.880019e+05,1.411865e+07
2024-09-10,15330806.5,6.250762e+08,1344.00,4.650864e+05,1.365356e+07
2024-09-11,15330806.5,0.000000e+00,1340.30,0.000000e+00,1.365356e+07
2024-09-12,15330806.5,5.286863e+08,1342.00,3.939540e+05,1.325961e+07
2024-09-13,15330806.5,5.196912e+08,1333.55,3.897051e+05,1.286990e+07
2024-09-14,15330806.5,0.000000e+00,1333.55,0.000000e+00,1.286990e+07
2024-09-15,15330806.5,0.000000e+00,1333.55,0.000000e+00,1.286990e+07
2024-09-16,15330806.5,0.000000e+00,1333.55,0.000000e+00,1.286990e+07
2024-09-17,15330806.5,0.000000e+00,1333.55,0.000000e+00,1.286990e+07
2024-09-18,15330806.5,0.000000e+00,1333.55,0.000000e+00,1.286990e+07
2024-09-19,15330806.5,7.272345e+08,1329.05,5.471837e+05,1.232272e+07
2024-09-20,15330806.5,1.931465e+09,1335.20,1.446574e+06,1.087614e+07
2024-09-21,15330806.5,0.000000e+00,1335.20,0.000000e+00,1.087614e+07
2024-09-22,15330806.5,0.000000e+00,1335.20,0.000000e+00,1.087614e+07
2024-09-23,15330806.5,7.268766e+08,1335.25,5.443749e+05,1.033177e+07
2024-09-24,15330806.5,1.282227e+09,1331.30,9.631392e+05,9.368629e+06
2024-09-25,15330806.5,0.000000e+00,1335.50,0.000000e+00,9.368629e+06
2024-09-26,15330806.5,4.058848e+08,1312.72,3.091938e+05,9.059435e+06
2024-09-27,15330806.5,0.000000e+00,1308.30,0.000000e+00,9.059435e+06
2024-09-28,15330806.5,0.000000e+00,1308.30,0.000000e+00,9.059435e+06
2024-09-29,15330806.5,0.000000e+00,1308.30,0.000000e+00,9.059435e+06
2024-09-30,15330806.5,0.000000e+00,1316.67,0.000000e+00,9.059435e+06
2024-10-01,15330806.5,0.000000e+00,1316.67,0.000000e+00,9.059435e+06

In [48]:
df['cash_krw'] = df['cash_usd'] * df['usdkrw']
# cols_to_keep = ['cash_usd', 'cash_krw']
# df = df[cols_to_keep]
df

,initial_balance_usd,amount_order,usdkrw,amount_usd,cash_usd,cash_krw
date,,,,,,
2024-09-01,15330806.5,0.000000e+00,1337.80,0.000000e+00,1.533081e+07,2.050955e+10
2024-09-02,15330806.5,6.145814e+08,1338.35,4.592083e+05,1.487160e+07,1.990340e+10
2024-09-03,15330806.5,0.000000e+00,1341.90,0.000000e+00,1.487160e+07,1.995620e+10
2024-09-04,15330806.5,0.000000e+00,1341.90,0.000000e+00,1.487160e+07,1.995620e+10
2024-09-05,15330806.5,5.294702e+08,1334.55,3.967407e+05,1.447486e+07,1.931742e+10
2024-09-06,15330806.5,9.106007e+07,1335.00,6.820979e+04,1.440665e+07,1.923287e+10
2024-09-07,15330806.5,0.000000e+00,1335.00,0.000000e+00,1.440665e+07,1.923287e+10
2024-09-08,15330806.5,0.000000e+00,1335.00,0.000000e+00,1.440665e+07,1.923287e+10
2024-09-09,15330806.5,3.844826e+08,1335.00,2.880019e+05,1.411865e+07,1.884839e+10
2024-09-10,15330806.5,6.250762e+08,1344.00,4.650864e+05,1.365356e+07,1.835038e+10
2024-09-11,15330806.5,0.000000e+00,1340.30,0.000000e+00,1.365356e+07,1.829987e+10
2024-09-12,15330806.5,5.286863e+08,1342.00,3.939540e+05,1.325961e+07,1.779439e+10
2024-09-13,15330806.5,5.196912e+08,1333.55,3.897051e+05,1.286990e+07,1.716266e+10
2024-09-14,15330806.5,0.000000e+00,1333.55,0.000000e+00,1.286990e+07,1.716266e+10
2024-09-15,15330806.5,0.000000e+00,1333.55,0.000000e+00,1.286990e+07,1.716266e+10
2024-09-16,15330806.5,0.000000e+00,1333.55,0.000000e+00,1.286990e+07,1.716266e+10
2024-09-17,15330806.5,0.000000e+00,1333.55,0.000000e+00,1.286990e+07,1.716266e+10
2024-09-18,15330806.5,0.000000e+00,1333.55,0.000000e+00,1.286990e+07,1.716266e+10
2024-09-19,15330806.5,7.272345e+08,1329.05,5.471837e+05,1.232272e+07,1.637751e+10
2024-09-20,15330806.5,1.931465e+09,1335.20,1.446574e+06,1.087614e+07,1.452183e+10
2024-09-21,15330806.5,0.000000e+00,1335.20,0.000000e+00,1.087614e+07,1.452183e+10
2024-09-22,15330806.5,0.000000e+00,1335.20,0.000000e+00,1.087614e+07,1.452183e+10
2024-09-23,15330806.5,7.268766e+08,1335.25,5.443749e+05,1.033177e+07,1.379549e+10
2024-09-24,15330806.5,1.282227e+09,1331.30,9.631392e+05,9.368629e+06,1.247246e+10
2024-09-25,15330806.5,0.000000e+00,1335.50,0.000000e+00,9.368629e+06,1.251180e+10
2024-09-26,15330806.5,4.058848e+08,1312.72,3.091938e+05,9.059435e+06,1.189250e+10
2024-09-27,15330806.5,0.000000e+00,1308.30,0.000000e+00,9.059435e+06,1.185246e+10
2024-09-28,15330806.5,0.000000e+00,1308.30,0.000000e+00,9.059435e+06,1.185246e+10
2024-09-29,15330806.5,0.000000e+00,1308.30,0.000000e+00,9.059435e+06,1.185246e+10
2024-09-30,15330806.5,0.000000e+00,1316.67,0.000000e+00,9.059435e+06,1.192829e+10
2024-10-01,15330806.5,0.000000e+00,1316.67,0.000000e+00,9.059435e+06,1.192829e+10

In [49]:
cols_to_keep = ['cash_usd', 'cash_krw', 'amount_order', 'amount_usd', 'usdkrw']
df = df[cols_to_keep]
df

                cash_usd      cash_krw
date
2024-09-01  1.533081e+07  2.050955e+10
2024-09-02  1.487160e+07  1.990340e+10
2024-09-03  1.487160e+07  1.995620e+10
2024-09-04  1.487160e+07  1.995620e+10
2024-09-05  1.447486e+07  1.931742e+10
2024-09-06  1.440665e+07  1.923287e+10
2024-09-07  1.440665e+07  1.923287e+10
2024-09-08  1.440665e+07  1.923287e+10
2024-09-09  1.411865e+07  1.884839e+10
2024-09-10  1.365356e+07  1.835038e+10
2024-09-11  1.365356e+07  1.829987e+10
2024-09-12  1.325961e+07  1.779439e+10
2024-09-13  1.286990e+07  1.716266e+10
2024-09-14  1.286990e+07  1.716266e+10
2024-09-15  1.286990e+07  1.716266e+10
2024-09-16  1.286990e+07  1.716266e+10
2024-09-17  1.286990e+07  1.716266e+10
2024-09-18  1.286990e+07  1.716266e+10
2024-09-19  1.232272e+07  1.637751e+10
2024-09-20  1.087614e+07  1.452183e+10
2024-09-21  1.087614e+07  1.452183e+10
2024-09-22  1.087614e+07  1.452183e+10
2024-09-23  1.033177e+07  1.379549e+10
2024-09-24  9.368629e+06  1.247246e+10
2024-09-25  9.368629e+06  1.251180e+10
2024-09-26  9.059435e+06  1.189250e+10
2024-09-27  9.059435e+06  1.185246e+10
2024-09-28  9.059435e+06  1.185246e+10
2024-09-29  9.059435e+06  1.185246e+10
2024-09-30  9.059435e+06  1.192829e+10
2024-10-01  9.059435e+06  1.192829e+10

In [52]:
df = trds.timeseries_evaluation
df = df.reindex(all_dates)
df['usdkrw'] = df.index.map(get_usdkrw_of_date)
df['stock_krw'] = df['total_evaluation']
df['stock_usd'] = df['stock_krw'] / df['usdkrw']
cols_to_keep = ['stock_usd', 'stock_krw']
df = df[cols_to_keep]
df

               stock_usd     stock_krw
date
2024-09-01           NaN           NaN
2024-09-02  4.576830e+05  6.125400e+08
2024-09-03  4.668492e+05  6.264650e+08
2024-09-04  4.564722e+05  6.125400e+08
2024-09-05  8.602900e+05  1.148100e+09
2024-09-06  9.215730e+05  1.230300e+09
2024-09-07           NaN           NaN
2024-09-08           NaN           NaN
2024-09-09  1.226554e+06  1.637450e+09
2024-09-10  1.637297e+06  2.200527e+09
2024-09-11  1.659073e+06  2.223656e+09
2024-09-12  2.102452e+06  2.821491e+09
2024-09-13  2.472397e+06  3.297064e+09
2024-09-14           NaN           NaN
2024-09-15           NaN           NaN
2024-09-16           NaN           NaN
2024-09-17           NaN           NaN
2024-09-18           NaN           NaN
2024-09-19  3.067076e+06  4.076298e+09
2024-09-20  4.612654e+06  6.158816e+09
2024-09-21           NaN           NaN
2024-09-22           NaN           NaN
2024-09-23  5.180135e+06  6.916775e+09
2024-09-24  6.198805e+06  8.252469e+09
2024-09-25  6.172932e+06  8.243950e+09
2024-09-26  6.719564e+06  8.820906e+09
2024-09-27  6.754555e+06  8.836985e+09
2024-09-28           NaN           NaN
2024-09-29           NaN           NaN
2024-09-30  6.580397e+06  8.664211e+09
2024-10-01           NaN           NaN

In [54]:
trds.history

,date,name,ticker,type,num_shares,average_price,consideration,commission,net_amount
0,2024-09-02,SeAH Steel Holdings,003030 KS,Buy,900,177645.666667,159881100.0,159881,160040981.0
1,2024-09-02,DN AUTOMOTIVE,007340 KS,Buy,2500,88110.280000,220275700.0,220276,220495976.0
2,2024-09-02,ORION,271560 KS,Buy,2200,91495.772727,201290700.0,201291,201491991.0
3,2024-09-02,DONG AH TIRE,282690 KS,Buy,2500,13007.988000,32519970.0,32520,32552490.0
4,2024-09-05,SeAH Steel Holdings,003030 KS,Buy,800,175209.750000,140167800.0,140168,140307968.0
5,2024-09-05,DN AUTOMOTIVE,007340 KS,Buy,2500,91637.240000,229093100.0,229093,229322193.0
6,2024-09-05,ORION,271560 KS,Buy,1800,88711.333333,159680400.0,159680,159840080.0
7,2024-09-06,DN AUTOMOTIVE,007340 KS,Buy,1000,90969.100000,90969100.0,90969,91060069.0
8,2024-09-09,SeAH Steel Holdings,003030 KS,Buy,500,174271.000000,87135500.0,87136,87222636.0
9,2024-09-09,DN AUTOMOTIVE,007340 KS,Buy,2231,93556.611385,208724800.0,208725,208933525.0
10,2024-09-09,ORION,271560 KS,Buy,1000,88238.200000,88238200.0,88238,88326438.0
11,2024-09-10,SK hynix,000660 KS,Buy,1200,155763.750000,186916500.0,186916,187103416.0
12,2024-09-10,SeAH Steel Holdings,003030 KS,Buy,200,167672.000000,33534400.0,33534,33567934.0
13,2024-09-10,DN AUTOMOTIVE,007340 KS,Buy,3500,90417.457143,316461100.0,316461,316777561.0
14,2024-09-10,ORION,271560 KS,Buy,1000,87539.700000,87539700.0,87540,87627240.0
15,2024-09-12,SK hynix,000660 KS,Buy,1200,169193.000000,203031600.0,203032,203234632.0
16,2024-09-12,SeAH Steel Holdings,003030 KS,Buy,350,174357.714286,61025200.0,61025,61086225.0
17,2024-09-12,DN AUTOMOTIVE,007340 KS,Buy,1500,92685.933333,139028900.0,139029,139167929.0
18,2024-09-12,ORION,271560 KS,Buy,1400,89337.428571,125072400.0,125072,125197472.0
19,2024-09-13,SK hynix,000660 KS,Buy,1200,162684.416667,195221300.0,195221,195416521.0
20,2024-09-13,SeAH Steel Holdings,003030 KS,Buy,350,171938.857143,60178600.0,60179,60238779.0
21,2024-09-13,DN AUTOMOTIVE,007340 KS,Buy,1500,92786.400000,139179600.0,139180,139318780.0
22,2024-09-13,ORION,271560 KS,Buy,1400,88994.642857,124592500.0,124592,124717092.0
23,2024-09-19,SeAH Steel Holdings,003030 KS,Buy,699,179751.359084,125646200.0,125646,125771846.0
24,2024-09-19,DN AUTOMOTIVE,007340 KS,Buy,1500,95794.600000,143691900.0,143692,143835592.0
25,2024-09-19,TKCORP.,023160 KS,Buy,8500,14075.971765,119645760.0,119646,119765406.0
26,2024-09-19,ORION,271560 KS,Buy,2000,90117.200000,180234400.0,180234,180414634.0
27,2024-09-19,WooriFinancialGroup,316140 KS,Buy,10000,15728.972000,157289720.0,157290,157447010.0
28,2024-09-20,SK hynix,000660 KS,Buy,800,157177.625000,125742100.0,125742,125867842.0
29,2024-09-20,SeAH Steel Holdings,003030 KS,Buy,1200,185050.583333,222060700.0,222061,222282761.0
30,2024-09-20,DongwonInd,006040 KS,Buy,2500,30808.260000,77020650.0,77021,77097671.0
31,2024-09-20,DN AUTOMOTIVE,007340 KS,Buy,4500,102093.444444,459420500.0,459420,459879920.0
32,2024-09-20,TKCORP.,023160 KS,Buy,15000,14427.932667,216418990.0,216419,216635409.0
33,2024-09-20,ORION,271560 KS,Buy,6000,90870.500000,545223000.0,545223,545768223.0
34,2024-09-20,WooriFinancialGroup,316140 KS,Buy,18000,15758.318889,283649740.0,283650,283933390.0
35,2024-09-23,SK hynix,000660 KS,Buy,600,161567.000000,96940200.0,96940,97037140.0
36,2024-09-23,SeAH Steel Holdings,003030 KS,Buy,250,184116.400000,46029100.0,46029,46075129.0
37,2024-09-23,DongwonInd,006040 KS,Buy,2500,31479.360000,78698400.0,78698,78777098.0
38,2024-09-23,DN AUTOMOTIVE,007340 KS,Buy,2000,100705.900000,201411800.0,201412,201613212.0
39,2024-09-23,TKCORP.,023160 KS,Buy,4500,14670.400000,66016800.0,66017,66082817.0
40,2024-09-23,ORION,271560 KS,Buy,2200,93522.636364,205749800.0,205750,205955550.0
41,2024-09-23,WooriFinancialGroup,316140 KS,Buy,2000,15652.175000,31304350.0,31304,31335654.0
42,2024-09-24,SeAH Steel Holdings,003030 KS,Buy,500,189070.400000,94535200.0,94535,94629735.0
43,2024-09-24,DongwonInd,006040 KS,Buy,2500,31417.300000,78543250.0,78543,78621793.0
44,2024-09-24,DN AUTOMOTIVE,007340 KS,Buy,6500,102404.169231,665627100.0,665627,666292727.0
45,2024-09-24,TKCORP.,023160 KS,Buy,7000,14643.414286,102503900.0,102504,102606404.0
46,2024-09-24,ORION,271560 KS,Buy,2000,91738.300000,183476600.0,183477,183660077.0
47,2024-09-24,WooriFinancialGroup,316140 KS,Buy,10000,15626.023000,156260230.0,156260,156416490.0
48,2024-09-26,SK hynix,000660 KS,Buy,500,179272.600000,89636300.0,89636,89725936.0
49,2024-09-26,SeAH Steel Holdings,003030 KS,Buy,250,190126.800000,47531700.0,47532,47579232.0
50,2024-09-26,DongwonInd,006040 KS,Buy,2500,31283.520000,78208800.0,78209,78287009.0
51,2024-09-26,TKCORP.,023160 KS,Buy,5000,14731.052000,73655260.0,73655,73728915.0
52,2024-09-26,ORION,271560 KS,Buy,800,95434.125000,76347300.0,76347,76423647.0
53,2024-09-26,WooriFinancialGroup,316140 KS,Buy,2500,16039.996000,40099990.0,40100,40140090.0

In [55]:
trds.pl

,date,ticker,name,num_shares,price_average,price_last,net_amount,evaluation,pl,return
0,2024-09-02,003030 KS,SEAH STEEL HOLDINGS CORP,900,177645.666667,174200.0,160040981.0,156780000.0,-3260981.0,-1.939629
1,2024-09-02,007340 KS,DN AUTOMOTIVE CORP,2500,88110.280000,102100.0,220495976.0,255250000.0,34754024.0,15.877512
2,2024-09-02,271560 KS,ORION CORP/REPUBLIC OF KOREA,2200,91495.772727,97500.0,201491991.0,214500000.0,13008009.0,6.562300
3,2024-09-02,282690 KS,DONG AH TIRE & RUBBER CO LTD,2500,13007.988000,13500.0,32552490.0,33750000.0,1197510.0,3.782384
4,2024-09-05,003030 KS,SEAH STEEL HOLDINGS CORP,800,175209.750000,174200.0,140307968.0,139360000.0,-947968.0,-0.576309
5,2024-09-05,007340 KS,DN AUTOMOTIVE CORP,2500,91637.240000,102100.0,229322193.0,255250000.0,25927807.0,11.417585
6,2024-09-05,271560 KS,ORION CORP/REPUBLIC OF KOREA,1800,88711.333333,97500.0,159840080.0,175500000.0,15659920.0,9.907039
7,2024-09-06,007340 KS,DN AUTOMOTIVE CORP,1000,90969.100000,102100.0,91060069.0,102100000.0,11039931.0,12.235913
8,2024-09-09,003030 KS,SEAH STEEL HOLDINGS CORP,500,174271.000000,174200.0,87222636.0,87100000.0,-122636.0,-0.040741
9,2024-09-09,007340 KS,DN AUTOMOTIVE CORP,2231,93556.611385,102100.0,208933525.0,227785100.0,18851575.0,9.131785
10,2024-09-09,271560 KS,ORION CORP/REPUBLIC OF KOREA,1000,88238.200000,97500.0,88326438.0,97500000.0,9173562.0,10.496361
11,2024-09-10,000660 KS,SK HYNIX INC,1200,155763.750000,174600.0,187103416.0,209520000.0,22416584.0,12.092833
12,2024-09-10,003030 KS,SEAH STEEL HOLDINGS CORP,200,167672.000000,174200.0,33567934.0,34840000.0,1272066.0,3.893316
13,2024-09-10,007340 KS,DN AUTOMOTIVE CORP,3500,90417.457143,102100.0,316777561.0,357350000.0,40572439.0,12.920672
14,2024-09-10,271560 KS,ORION CORP/REPUBLIC OF KOREA,1000,87539.700000,97500.0,87627240.0,97500000.0,9872760.0,11.378038
15,2024-09-12,000660 KS,SK HYNIX INC,1200,169193.000000,174600.0,203234632.0,209520000.0,6285368.0,3.195759
16,2024-09-12,003030 KS,SEAH STEEL HOLDINGS CORP,350,174357.714286,174200.0,61086225.0,60970000.0,-116225.0,-0.090454
17,2024-09-12,007340 KS,DN AUTOMOTIVE CORP,1500,92685.933333,102100.0,139167929.0,153150000.0,13982071.0,10.156953
18,2024-09-12,271560 KS,ORION CORP/REPUBLIC OF KOREA,1400,89337.428571,97500.0,125197472.0,136500000.0,11302528.0,9.136788
19,2024-09-13,000660 KS,SK HYNIX INC,1200,162684.416667,174600.0,195416521.0,209520000.0,14103479.0,7.324354
20,2024-09-13,003030 KS,SEAH STEEL HOLDINGS CORP,350,171938.857143,174200.0,60238779.0,60970000.0,731221.0,1.315085
21,2024-09-13,007340 KS,DN AUTOMOTIVE CORP,1500,92786.400000,102100.0,139318780.0,153150000.0,13831220.0,10.037678
22,2024-09-13,271560 KS,ORION CORP/REPUBLIC OF KOREA,1400,88994.642857,97500.0,124717092.0,136500000.0,11782908.0,9.557156
23,2024-09-19,003030 KS,SEAH STEEL HOLDINGS CORP,699,179751.359084,174200.0,125771846.0,121765800.0,-4006046.0,-3.088354
24,2024-09-19,007340 KS,DN AUTOMOTIVE CORP,1500,95794.600000,102100.0,143835592.0,153150000.0,9314408.0,6.582208
25,2024-09-19,023160 KS,TK CORPORATION,8500,14075.971765,13660.0,119765406.0,116110000.0,-3655406.0,-2.955190
26,2024-09-19,271560 KS,ORION CORP/REPUBLIC OF KOREA,2000,90117.200000,97500.0,180414634.0,195000000.0,14585366.0,8.192443
27,2024-09-19,316140 KS,WOORI FINANCIAL GROUP INC,10000,15728.972000,15500.0,157447010.0,155000000.0,-2447010.0,-1.455734
28,2024-09-20,000660 KS,SK HYNIX INC,800,157177.625000,174600.0,125867842.0,139680000.0,13812158.0,11.084513
29,2024-09-20,003030 KS,SEAH STEEL HOLDINGS CORP,1200,185050.583333,174200.0,222282761.0,209040000.0,-13242761.0,-5.863577
30,2024-09-20,006040 KS,DONGWON INDUSTRIES CO LTD,2500,30808.260000,31000.0,77097671.0,77500000.0,402329.0,0.622366
31,2024-09-20,007340 KS,DN AUTOMOTIVE CORP,4500,102093.444444,102100.0,459879920.0,459450000.0,-429920.0,0.006421
32,2024-09-20,023160 KS,TK CORPORATION,15000,14427.932667,13660.0,216635409.0,204900000.0,-11735409.0,-5.322541
33,2024-09-20,271560 KS,ORION CORP/REPUBLIC OF KOREA,6000,90870.500000,97500.0,545768223.0,585000000.0,39231777.0,7.295547
34,2024-09-20,316140 KS,WOORI FINANCIAL GROUP INC,18000,15758.318889,15500.0,283933390.0,279000000.0,-4933390.0,-1.639254
35,2024-09-23,000660 KS,SK HYNIX INC,600,161567.000000,174600.0,97037140.0,104760000.0,7722860.0,8.066623
36,2024-09-23,003030 KS,SEAH STEEL HOLDINGS CORP,250,184116.400000,174200.0,46075129.0,43550000.0,-2525129.0,-5.385941
37,2024-09-23,006040 KS,DONGWON INDUSTRIES CO LTD,2500,31479.360000,31000.0,78777098.0,77500000.0,-1277098.0,-1.522776
38,2024-09-23,007340 KS,DN AUTOMOTIVE CORP,2000,100705.900000,102100.0,201613212.0,204200000.0,2586788.0,1.384328
39,2024-09-23,023160 KS,TK CORPORATION,4500,14670.400000,13660.0,66082817.0,61470000.0,-4612817.0,-6.887338
40,2024-09-23,271560 KS,ORION CORP/REPUBLIC OF KOREA,2200,93522.636364,97500.0,205955550.0,214500000.0,8544450.0,4.252835
41,2024-09-23,316140 KS,WOORI FINANCIAL GROUP INC,2000,15652.175000,15500.0,31335654.0,31000000.0,-335654.0,-0.972229
42,2024-09-24,003030 KS,SEAH STEEL HOLDINGS CORP,500,189070.400000,174200.0,94629735.0,87100000.0,-7529735.0,-7.865007
43,2024-09-24,006040 KS,DONGWON INDUSTRIES CO LTD,2500,31417.300000,31000.0,78621793.0,77500000.0,-1121793.0,-1.328249
44,2024-09-24,007340 KS,DN AUTOMOTIVE CORP,6500,102404.169231,102100.0,666292727.0,663650000.0,-2642727.0,-0.297028
45,2024-09-24,023160 KS,TK CORPORATION,7000,14643.414286,13660.0,102606404.0,95620000.0,-6986404.0,-6.715744
46,2024-09-24,271560 KS,ORION CORP/REPUBLIC OF KOREA,2000,91738.300000,97500.0,183660077.0,195000000.0,11339923.0,6.280583
47,2024-09-24,316140 KS,WOORI FINANCIAL GROUP INC,10000,15626.023000,15500.0,156416490.0,155000000.0,-1416490.0,-0.806494
48,2024-09-26,000660 KS,SK HYNIX INC,500,179272.600000,174600.0,89725936.0,87300000.0,-2425936.0,-2.606422
49,2024-09-26,003030 KS,SEAH STEEL HOLDINGS CORP,250,190126.800000,174200.0,47579232.0,43550000.0,-4029232.0,-8.376936
50,2024-09-26,006040 KS,DONGWON INDUSTRIES CO LTD,2500,31283.520000,31000.0,78287009.0,77500000.0,-787009.0,-0.906292
51,2024-09-26,023160 KS,TK CORPORATION,5000,14731.052000,13660.0,73728915.0,68300000.0,-5428915.0,-7.270710
52,2024-09-26,271560 KS,ORION CORP/REPUBLIC OF KOREA,800,95434.125000,97500.0,76423647.0,78000000.0,1576353.0,2.164713
53,2024-09-26,316140 KS,WOORI FINANCIAL GROUP INC,2500,16039.996000,15500.0,40140090.0,38750000.0,-1390090.0,-3.366559

In [7]:
trds.trades[0].timeseries

,"003030 KS: (2024-09-02, 900)","007340 KS: (2024-09-02, 2500)","271560 KS: (2024-09-02, 2200)","282690 KS: (2024-09-02, 2500)",evaluation: 2024-09-02,cumreturn: 2024-09-02
date,,,,,,
2024-09-02,158580000,220500000,200860000,32600000,612540000,0.000000
2024-09-03,163800000,231250000,197340000,34075000,626465000,2.273321
2024-09-04,158400000,225250000,195140000,33750000,612540000,0.000000
2024-09-05,158850000,229750000,195140000,33750000,617490000,0.808110
2024-09-06,159750000,226000000,193820000,33750000,613320000,0.127339
2024-09-09,157230000,235500000,195360000,33750000,621840000,1.518268
2024-09-10,150660000,224750000,192060000,33750000,601220000,-1.848043
2024-09-11,150210000,229500000,192060000,33750000,605520000,-1.146048
2024-09-12,157140000,234750000,196240000,33750000,621880000,1.524798
2024-09-13,154710000,231000000,195800000,33750000,615260000,0.444053
2024-09-19,162000000,239750000,198440000,33750000,633940000,3.493649
2024-09-20,168300000,255500000,199540000,33750000,657090000,7.272994
2024-09-23,163980000,253000000,205920000,33750000,656650000,7.201162
2024-09-24,172170000,255250000,202620000,33750000,663790000,8.366801
2024-09-25,166500000,255250000,206580000,33750000,662080000,8.087635
2024-09-26,169920000,255250000,210540000,33750000,669460000,9.292454
2024-09-27,162450000,255250000,219120000,33750000,670570000,9.473667
2024-09-30,156780000,255250000,214500000,33750000,660280000,7.793777

In [63]:
trade_objs = trds.trades
dfs = [trade.timeseries.iloc[:, -2:-1] for trade in trade_objs]
df = pd.concat(dfs, axis=1)
df = df.fillna(0)
df = df.reindex(all_dates)
df = df.ffill()
df = df.fillna(0)
df

,evaluation: 2024-09-02,evaluation: 2024-09-05,evaluation: 2024-09-06,evaluation: 2024-09-09,evaluation: 2024-09-10,evaluation: 2024-09-12,evaluation: 2024-09-13,evaluation: 2024-09-19,evaluation: 2024-09-20,evaluation: 2024-09-23,evaluation: 2024-09-24,evaluation: 2024-09-26
date,,,,,,,,,,,,
2024-09-01,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.000000e+00,0.0,0.000000e+00,0.0
2024-09-02,612540000.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.000000e+00,0.0,0.000000e+00,0.0
2024-09-03,626465000.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.000000e+00,0.0,0.000000e+00,0.0
2024-09-04,612540000.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.000000e+00,0.0,0.000000e+00,0.0
2024-09-05,617490000.0,530610000.0,0.0,0.0,0.0,0.0,0.0,0.0,0.000000e+00,0.0,0.000000e+00,0.0
2024-09-06,613320000.0,526580000.0,90400000.0,0.0,0.0,0.0,0.0,0.0,0.000000e+00,0.0,0.000000e+00,0.0
2024-09-07,613320000.0,526580000.0,90400000.0,0.0,0.0,0.0,0.0,0.0,0.000000e+00,0.0,0.000000e+00,0.0
2024-09-08,613320000.0,526580000.0,90400000.0,0.0,0.0,0.0,0.0,0.0,0.000000e+00,0.0,0.000000e+00,0.0
2024-09-09,621840000.0,535100000.0,94200000.0,386310200.0,0.0,0.0,0.0,0.0,0.000000e+00,0.0,0.000000e+00,0.0
2024-09-10,601220000.0,515810000.0,89900000.0,371566900.0,622030000.0,0.0,0.0,0.0,0.000000e+00,0.0,0.000000e+00,0.0
2024-09-11,605520000.0,520160000.0,91800000.0,375555800.0,630620000.0,0.0,0.0,0.0,0.000000e+00,0.0,0.000000e+00,0.0
2024-09-12,621880000.0,534990000.0,93900000.0,385990900.0,655330000.0,529400000.0,0.0,0.0,0.000000e+00,0.0,0.000000e+00,0.0
2024-09-13,615260000.0,528720000.0,92400000.0,381094400.0,642140000.0,518725000.0,518725000.0,0.0,0.000000e+00,0.0,0.000000e+00,0.0
2024-09-14,615260000.0,528720000.0,92400000.0,381094400.0,642140000.0,518725000.0,518725000.0,0.0,0.000000e+00,0.0,0.000000e+00,0.0
2024-09-15,615260000.0,528720000.0,92400000.0,381094400.0,642140000.0,518725000.0,518725000.0,0.0,0.000000e+00,0.0,0.000000e+00,0.0
2024-09-16,615260000.0,528720000.0,92400000.0,381094400.0,642140000.0,518725000.0,518725000.0,0.0,0.000000e+00,0.0,0.000000e+00,0.0
2024-09-17,615260000.0,528720000.0,92400000.0,381094400.0,642140000.0,518725000.0,518725000.0,0.0,0.000000e+00,0.0,0.000000e+00,0.0
2024-09-18,615260000.0,528720000.0,92400000.0,381094400.0,642140000.0,518725000.0,518725000.0,0.0,0.000000e+00,0.0,0.000000e+00,0.0
2024-09-19,633940000.0,546110000.0,95900000.0,394152900.0,645210000.0,516490000.0,516490000.0,728005000.0,0.000000e+00,0.0,0.000000e+00,0.0
2024-09-20,657090000.0,568360000.0,102200000.0,412208200.0,674320000.0,534250000.0,534250000.0,745333000.0,1.930805e+09,0.0,0.000000e+00,0.0
2024-09-21,657090000.0,568360000.0,102200000.0,412208200.0,674320000.0,534250000.0,534250000.0,745333000.0,1.930805e+09,0.0,0.000000e+00,0.0
2024-09-22,657090000.0,568360000.0,102200000.0,412208200.0,674320000.0,534250000.0,534250000.0,745333000.0,1.930805e+09,0.0,0.000000e+00,0.0
2024-09-23,656650000.0,567240000.0,101200000.0,410477200.0,678640000.0,541010000.0,541010000.0,747642800.0,1.945920e+09,726985000.0,0.000000e+00,0.0
2024-09-24,663790000.0,574070000.0,102100000.0,415535100.0,683910000.0,545245000.0,545245000.0,754028700.0,1.956060e+09,729415000.0,1.283070e+09,0.0
2024-09-25,662080000.0,572270000.0,102100000.0,414185100.0,686610000.0,547720000.0,547720000.0,749255000.0,1.952660e+09,730470000.0,1.278880e+09,0.0
2024-09-26,669460000.0,578550000.0,102100000.0,417885100.0,707890000.0,570290000.0,570290000.0,762811200.0,1.994580e+09,747760000.0,1.292380e+09,406910000.0
2024-09-27,670570000.0,578930000.0,102100000.0,417635100.0,713610000.0,576325000.0,576325000.0,756799500.0,1.996495e+09,752930000.0,1.289385e+09,405880000.0
2024-09-28,670570000.0,578930000.0,102100000.0,417635100.0,713610000.0,576325000.0,576325000.0,756799500.0,1.996495e+09,752930000.0,1.289385e+09,405880000.0
2024-09-29,670570000.0,578930000.0,102100000.0,417635100.0,713610000.0,576325000.0,576325000.0,756799500.0,1.996495e+09,752930000.0,1.289385e+09,405880000.0
2024-09-30,660280000.0,570110000.0,102100000.0,412385100.0,699210000.0,560140000.0,560140000.0,741025800.0,1.954570e+09,736980000.0,1.273870e+09,393400000.0
2024-10-01,660280000.0,570110000.0,102100000.0,412385100.0,699210000.0,560140000.0,560140000.0,741025800.0,1.954570e+09,736980000.0,1.273870e+09,393400000.0