In [1]:
from cayman_office_system import *

INFO:shining_pebbles:Shining Pebbles package initialized
INFO:numexpr.utils:Note: NumExpr detected 10 cores but "NUMEXPR_MAX_THREADS" not set, so enforcing safe limit of 8.
INFO:numexpr.utils:NumExpr defaulting to 8 threads.

In [2]:
trades = Trades()

| import trade of (date, index) = (2024-09-02, None)
|- cash flow of trade: -614581438.0
| import trade of (date, index) = (2024-09-05, None)
|- cash flow of trade: -529470241.0
| import trade of (date, index) = (2024-09-06, None)
|- cash flow of trade: -91060069.0
| import trade of (date, index) = (2024-09-09, None)
|- cash flow of trade: -384482599.0
| import trade of (date, index) = (2024-09-10, None)
|- cash flow of trade: -625076151.0
| import trade of (date, index) = (2024-09-12, None)
|- cash flow of trade: -528686258.0
| import trade of (date, index) = (2024-09-13, None)
|- cash flow of trade: -519691172.0
| import trade of (date, index) = (2024-09-19, None)
|- cash flow of trade: -727234488.0
| import trade of (date, index) = (2024-09-20, None)
|- cash flow of trade: -1931465216.0
| import trade of (date, index) = (2024-09-23, None)
|- cash flow of trade: -726876600.0
| import trade of (date, index) = (2024-09-24, None)
|- cash flow of trade: -1282227226.0
| import trade of (date, index) = (2024-09-26, None)
|- cash flow of trade: -405884829.0
| import trade of (date, index) = (2024-10-08, None)
|- cash flow of trade: -670806496.0
| import trade of (date, index) = (2024-10-10, None)
|- cash flow of trade: -1479583697.0
| import trade of (date, index) = (2024-10-11, None)
|- cash flow of trade: -341436216.0
| import trade of (date, index) = (2024-10-15, None)
|- cash flow of trade: -871019390.0
| import trade of (date, index) = (2024-10-16, None)
|- cash flow of trade: 1136647412.0
| import trade of (date, index) = (2024-10-17, None)
|- cash flow of trade: -480907757.0
| import trade of (date, index) = (2024-10-21, None)
|- cash flow of trade: -635232077.0
| import trade of (date, index) = (2024-10-24, None)
|- cash flow of trade: -101252902.0
| append synthetic trade of Sell (date) = (2024-10-07)
|- cash flow of synthetic trade: 2984485100.0
| append synthetic trade of Sell (date) = (2024-10-07)
|- cash flow of synthetic trade: 33750000.0
| append synthetic trade of Buy (date) = (2024-10-08)
|- cash flow of synthetic trade: -2843520000.0

In [3]:
ts = Timeseries(trades=trades)

In [22]:
frame = ts.frame
valuation = ts.valuation.rename(columns={'total_valuation': 'stock: krw'})
df = frame.merge(valuation, how='left', left_index=True, right_index=True)
df['stock: krw'] = df['stock: krw'].fillna(0)

df.loc[df.index[0], 'stock: usd'] = df.loc[df.index[0], 'stock: krw'] / df.loc[df.index[0], 'usdkrw']
df.loc[df.index[0], 'cash: usd'] = df.loc[df.index[0], 'initial_balance: usd']
df.loc[df.index[0], 'cash: krw'] = df.loc[df.index[0], 'cash: usd'] * df.loc[df.index[0], 'usdkrw']
df.loc[df.index[0], 'nav: krw'] = df.loc[df.index[0], 'cash: krw'] + df.loc[df.index[0], 'stock: krw']
df.loc[df.index[0], 'nav: usd'] = df.loc[df.index[0], 'cash: usd'] + df.loc[df.index[0], 'stock: usd']
df.loc[df.index[1], 'initial_balance: usd'] = df.loc[df.index[0], 'cash: usd']

# df.loc[df.index[1], 'stock: usd'] = df.loc[df.index[1], 'stock: krw'] / df.loc[df.index[1], 'usdkrw']
# df.loc[df.index[1], 'cash: usd'] = df.loc[df.index[1], 'initial_balance: usd']
# df.loc[df.index[1], 'cash: krw'] = df.loc[df.index[1], 'cash: usd'] * df.loc[df.index[1], 'usdkrw']
# df.loc[df.index[1], 'nav: krw'] = df.loc[df.index[1], 'cash: krw'] + df.loc[df.index[1], 'stock: krw']
# df.loc[df.index[1], 'nav: usd'] = df.loc[df.index[1], 'cash: usd'] + df.loc[df.index[1], 'stock: usd']
# df.loc[df.index[2], 'initial_balance: usd'] = df.loc[df.index[1], 'cash: usd']

df

,initial_balance: usd,usdkrw,stock: krw,stock: usd,cash: usd,cash: krw,nav: krw,nav: usd
date,,,,,,,,
2024-09-01,15789908.45,1337.80,0.000000e+00,0.000000,15789908.45,2.112374e+10,2.112374e+10,1.578991e+07
2024-09-02,15789908.45,1338.35,6.136900e+08,458542.234841,15789908.45,2.113242e+10,2.174611e+10,1.624845e+07
2024-09-03,15789908.45,1341.90,6.261400e+08,NaN,NaN,NaN,NaN,NaN
2024-09-04,NaN,1341.90,6.125400e+08,NaN,NaN,NaN,NaN,NaN
2024-09-05,NaN,1334.55,1.148100e+09,NaN,NaN,NaN,NaN,NaN
2024-09-06,NaN,1335.00,1.230300e+09,NaN,NaN,NaN,NaN,NaN
2024-09-07,NaN,1335.00,1.230300e+09,NaN,NaN,NaN,NaN,NaN
2024-09-08,NaN,1335.00,1.230300e+09,NaN,NaN,NaN,NaN,NaN
2024-09-09,NaN,1335.00,1.637450e+09,NaN,NaN,NaN,NaN,NaN
2024-09-10,NaN,1344.00,2.200527e+09,NaN,NaN,NaN,NaN,NaN
2024-09-11,NaN,1340.30,2.223656e+09,NaN,NaN,NaN,NaN,NaN
2024-09-12,NaN,1342.00,2.821491e+09,NaN,NaN,NaN,NaN,NaN
2024-09-13,NaN,1333.55,3.297064e+09,NaN,NaN,NaN,NaN,NaN
2024-09-14,NaN,1333.55,3.297064e+09,NaN,NaN,NaN,NaN,NaN
2024-09-15,NaN,1333.55,3.297064e+09,NaN,NaN,NaN,NaN,NaN
2024-09-16,NaN,1333.55,3.297064e+09,NaN,NaN,NaN,NaN,NaN
2024-09-17,NaN,1333.55,3.297064e+09,NaN,NaN,NaN,NaN,NaN
2024-09-18,NaN,1333.55,3.297064e+09,NaN,NaN,NaN,NaN,NaN
2024-09-19,NaN,1329.05,4.076298e+09,NaN,NaN,NaN,NaN,NaN
2024-09-20,NaN,1335.20,6.158816e+09,NaN,NaN,NaN,NaN,NaN
2024-09-21,NaN,1335.20,6.158816e+09,NaN,NaN,NaN,NaN,NaN
2024-09-22,NaN,1335.20,6.158816e+09,NaN,NaN,NaN,NaN,NaN
2024-09-23,NaN,1335.25,6.916775e+09,NaN,NaN,NaN,NaN,NaN
2024-09-24,NaN,1331.30,8.252469e+09,NaN,NaN,NaN,NaN,NaN
2024-09-25,NaN,1335.50,8.243950e+09,NaN,NaN,NaN,NaN,NaN
2024-09-26,NaN,1317.35,8.820906e+09,NaN,NaN,NaN,NaN,NaN
2024-09-27,NaN,1310.55,8.836985e+09,NaN,NaN,NaN,NaN,NaN
2024-09-28,NaN,1310.55,8.836985e+09,NaN,NaN,NaN,NaN,NaN
2024-09-29,NaN,1310.55,8.836985e+09,NaN,NaN,NaN,NaN,NaN
2024-09-30,NaN,1314.70,8.664211e+09,NaN,NaN,NaN,NaN,NaN
2024-10-01,NaN,1314.70,8.664211e+09,NaN,NaN,NaN,NaN,NaN
2024-10-02,NaN,1322.95,8.579484e+09,NaN,NaN,NaN,NaN,NaN
2024-10-03,NaN,1322.95,8.579484e+09,NaN,NaN,NaN,NaN,NaN
2024-10-04,NaN,1322.95,8.640246e+09,NaN,NaN,NaN,NaN,NaN
2024-10-05,NaN,1322.95,8.640246e+09,NaN,NaN,NaN,NaN,NaN
2024-10-06,NaN,1322.95,8.640246e+09,NaN,NaN,NaN,NaN,NaN
2024-10-07,NaN,1344.25,5.718212e+09,NaN,NaN,NaN,NaN,NaN
2024-10-08,NaN,1346.30,9.207732e+09,NaN,NaN,NaN,NaN,NaN
2024-10-09,NaN,1346.30,9.207732e+09,NaN,NaN,NaN,NaN,NaN
2024-10-10,NaN,1354.00,1.074210e+10,NaN,NaN,NaN,NaN,NaN
2024-10-11,NaN,1350.95,1.097780e+10,NaN,NaN,NaN,NaN,NaN
2024-10-12,NaN,1350.95,1.097780e+10,NaN,NaN,NaN,NaN,NaN
2024-10-13,NaN,1350.95,1.097780e+10,NaN,NaN,NaN,NaN,NaN
2024-10-14,NaN,1357.80,1.111113e+10,NaN,NaN,NaN,NaN,NaN
2024-10-15,NaN,1364.80,1.202829e+10,NaN,NaN,NaN,NaN,NaN
2024-10-16,NaN,1364.55,1.074253e+10,NaN,NaN,NaN,NaN,NaN
2024-10-17,NaN,1372.50,1.128989e+10,NaN,NaN,NaN,NaN,NaN
2024-10-18,NaN,1368.80,1.120600e+10,NaN,NaN,NaN,NaN,NaN
2024-10-19,NaN,1368.80,1.120600e+10,NaN,NaN,NaN,NaN,NaN
2024-10-20,NaN,1368.80,1.120600e+10,NaN,NaN,NaN,NaN,NaN
2024-10-21,NaN,1378.20,1.169876e+10,NaN,NaN,NaN,NaN,NaN
2024-10-22,NaN,1377.30,1.155679e+10,NaN,NaN,NaN,NaN,NaN
2024-10-23,NaN,1382.30,1.153810e+10,NaN,NaN,NaN,NaN,NaN
2024-10-24,NaN,1380.55,1.173314e+10,NaN,NaN,NaN,NaN,NaN
2024-10-25,NaN,1380.55,1.163505e+10,NaN,NaN,NaN,NaN,NaN

In [4]:
ts.frame

            initial_balance: usd   usdkrw
date
2024-09-01           15789908.45  1337.80
2024-09-02                   NaN  1338.35
2024-09-03                   NaN  1341.90
2024-09-04                   NaN  1341.90
2024-09-05                   NaN  1334.55
2024-09-06                   NaN  1335.00
2024-09-07                   NaN  1335.00
2024-09-08                   NaN  1335.00
2024-09-09                   NaN  1335.00
2024-09-10                   NaN  1344.00
2024-09-11                   NaN  1340.30
2024-09-12                   NaN  1342.00
2024-09-13                   NaN  1333.55
2024-09-14                   NaN  1333.55
2024-09-15                   NaN  1333.55
2024-09-16                   NaN  1333.55
2024-09-17                   NaN  1333.55
2024-09-18                   NaN  1333.55
2024-09-19                   NaN  1329.05
2024-09-20                   NaN  1335.20
2024-09-21                   NaN  1335.20
2024-09-22                   NaN  1335.20
2024-09-23                   NaN  1335.25
2024-09-24                   NaN  1331.30
2024-09-25                   NaN  1335.50
2024-09-26                   NaN  1317.35
2024-09-27                   NaN  1310.55
2024-09-28                   NaN  1310.55
2024-09-29                   NaN  1310.55
2024-09-30                   NaN  1314.70
2024-10-01                   NaN  1314.70
2024-10-02                   NaN  1322.95
2024-10-03                   NaN  1322.95
2024-10-04                   NaN  1322.95
2024-10-05                   NaN  1322.95
2024-10-06                   NaN  1322.95
2024-10-07                   NaN  1344.25
2024-10-08                   NaN  1346.30
2024-10-09                   NaN  1346.30
2024-10-10                   NaN  1354.00
2024-10-11                   NaN  1350.95
2024-10-12                   NaN  1350.95
2024-10-13                   NaN  1350.95
2024-10-14                   NaN  1357.80
2024-10-15                   NaN  1364.80
2024-10-16                   NaN  1364.55
2024-10-17                   NaN  1372.50
2024-10-18                   NaN  1368.80
2024-10-19                   NaN  1368.80
2024-10-20                   NaN  1368.80
2024-10-21                   NaN  1378.20
2024-10-22                   NaN  1377.30
2024-10-23                   NaN  1382.30
2024-10-24                   NaN  1380.55
2024-10-25                   NaN  1380.55

In [5]:
ts.valuation

            total_valuation
date
2024-09-02     6.136900e+08
2024-09-03     6.261400e+08
2024-09-04     6.125400e+08
2024-09-05     1.148100e+09
2024-09-06     1.230300e+09
2024-09-07     1.230300e+09
2024-09-08     1.230300e+09
2024-09-09     1.637450e+09
2024-09-10     2.200527e+09
2024-09-11     2.223656e+09
2024-09-12     2.821491e+09
2024-09-13     3.297064e+09
2024-09-14     3.297064e+09
2024-09-15     3.297064e+09
2024-09-16     3.297064e+09
2024-09-17     3.297064e+09
2024-09-18     3.297064e+09
2024-09-19     4.076298e+09
2024-09-20     6.158816e+09
2024-09-21     6.158816e+09
2024-09-22     6.158816e+09
2024-09-23     6.916775e+09
2024-09-24     8.252469e+09
2024-09-25     8.243950e+09
2024-09-26     8.820906e+09
2024-09-27     8.836985e+09
2024-09-28     8.836985e+09
2024-09-29     8.836985e+09
2024-09-30     8.664211e+09
2024-10-01     8.664211e+09
2024-10-02     8.579484e+09
2024-10-03     8.579484e+09
2024-10-04     8.640246e+09
2024-10-05     8.640246e+09
2024-10-06     8.640246e+09
2024-10-07     5.718212e+09
2024-10-08     9.207732e+09
2024-10-09     9.207732e+09
2024-10-10     1.074210e+10
2024-10-11     1.097780e+10
2024-10-12     1.097780e+10
2024-10-13     1.097780e+10
2024-10-14     1.111113e+10
2024-10-15     1.202829e+10
2024-10-16     1.074253e+10
2024-10-17     1.128989e+10
2024-10-18     1.120600e+10
2024-10-19     1.120600e+10
2024-10-20     1.120600e+10
2024-10-21     1.169876e+10
2024-10-22     1.155679e+10
2024-10-23     1.153810e+10
2024-10-24     1.173314e+10
2024-10-25     1.163505e+10